# Étape 1 : Extraction des Flux RSS

In [ ]:
# %pip install feedparser

In [1]:
import feedparser
url_alerte = "https://www.cert.ssi.gouv.fr/alerte/feed/"
rss_alerte_feed = feedparser.parse(url_alerte)
for entry in rss_alerte_feed.entries:
    print("Titre :", entry.title)
    print("Description:", entry.description)
    print("Lien :", entry.link)
    print("Date :", entry.published)

url_avis = "https://www.cert.ssi.gouv.fr/avis/feed/"
rss_avis_feed = feedparser.parse(url_avis)
for entry in rss_avis_feed.entries:
    print("Titre :", entry.title)
    print("Description:", entry.description)
    print("Lien :", entry.link)
    print("Date :", entry.published)

Titre : [MàJ] Vulnérabilité dans Zimbra Collaboration Suite (17 juillet 2023)
Description: \[Mise à jour du 26 juillet 2023\] Publication du correctif de sécurité par l'éditeur Le 26 juillet 2023, l'éditeur a publié un correctif de sécurité \[1\] pour cette vulnérabilité immatriculée CVE-2023-37580. Il est donc fortement recommandé de déployer le correctif P41 pour toutes les versions...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2023-ALE-007/
Date : Mon, 17 Jul 2023 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Citrix NetScaler ADC et NetScaler Gateway (19 juillet 2023)
Description: Le 18 juillet 2023, Citrix a publié un avis de sécurité concernant plusieurs vulnérabilités. La plus critique, dont l'identifiant CVE est CVE-2023-3519, permet à un attaquant non authentifié d'exécuter du code arbitraire à distance. L'équipement est vulnérable s'il est configuré en tant que...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2023-ALE-008/
Date : Wed, 19 Jul 2023 00:00:00 +0000
Titre : Multiples vulnérabilités dans Exim (02 octobre 2023)
Description: Le 27 septembre 2023, Zero Day Initiative (ZDI) a publié six avis de sécurité \[1\] concernant des vulnérabilités de type zéro-jour affectant les versions antérieures à 4.96.1 ou 4.97 de l'agent de transfert de courriels (*Mail Transfer Agent* ou *MTA*) Exim. Le 1er octobre 2023, l'éditeur a...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2023-ALE-010/
Date : Mon, 02 Oct 2023 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités dans Cisco IOS XE (17 octobre 2023)
Description: \[Mise à jour du 02 novembre 2023\] La version 17.3.8a est disponible. \[Mise à jour du 31 octobre 2023\] Les détails techniques de la vulnérabilité CVE-2023-20198 sont désormais disponibles publiquement. Cette vulnérabilité était déjà massivement exploitée. Tous les équipements exposant...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2023-ALE-011/
Date : Tue, 17 Oct 2023 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Citrix NetScaler ADC et NetScaler Gateway (23 octobre 2023)
Description: \[Mise à jour du 22 novembre 2023\] L'éditeur a publié un document \[3\] le 20 novembre 2023 listant les différents journaux à analyser ainsi que les éléments à rechercher pour identifier une activité pouvant être liée à une compromission. Par ailleurs, la CISA a publié un avis de sécurité le 21...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2023-ALE-012/
Date : Mon, 23 Oct 2023 00:00:00 +0000
Titre : Vulnérabilité dans Apache Struts 2 (13 décembre 2023)
Description: Le 4 décembre 2023, Apache a publié un avis de sécurité concernant la vulnérabilité critique CVE-2023-50164 concernant le cadriciel Struts 2. Cette vulnérabilité permet à un attaquant non authentifié de téléverser une porte dérobée sur un serveur vulnérable, et ainsi exécuter du code arbitraire à...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2023-ALE-013/
Date : Wed, 13 Dec 2023 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités dans Ivanti Connect Secure et Policy Secure Gateways (11 janvier 2024)
Description: [Mise à jour du 4 mars 2024] Ivanti a publié le 29 février des recommandations de résolution pour les Ivanti Connect Secure ou Policy Secure en machine virtuelle [16]. [Mise à jour du 15 février 2024] l'éditeur a publié le 15 février des correctifs pour les versions suivantes, qui n'en...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-001/
Date : Thu, 11 Jan 2024 00:00:00 +0000
Titre : [MàJ] Multiples Vulnérabilités dans GitLab (12 janvier 2024)
Description: \[Mise à jour du 29 janvier 2024\] Le 25 janvier 2024, l'éditeur a publié un avis de sécurité concernant plusieurs vulnérabilités affectant GitLab CE et EE. La vulnérabilité CVE-2024-0402 est considérée critique avec un score CVSSv3 de 9,9. Elle permet à un attaquant authentifié d'écrire des...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-002/
Date : Fri, 12 Jan 2024 00:00:00 +0000
Titre : [MàJ] Incident affectant les solutions AnyDesk (05 février 2024)
Description: \[Mise à jour du 27 février 2024\] Le 29 janvier 2024 l'ANSSI a été alertée par le BSI que l'éditeur AnyDesk Software GmbH a été victime d'une fuite de données. Le code source des applications développées par l'éditeur ainsi que des certificats et clés privées pourraient avoir été dérobés. De...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-003/
Date : Mon, 05 Feb 2024 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Fortinet FortiOS (09 février 2024)
Description: \[Mise à jour du 19 mars 2024\] Le CERT-FR a connaissance de codes d'exploitation publics et de nouvelles tentatives d'exploitation. Le 8 février 2024, Fortinet a publié l'avis de sécurité concernant la vulnérabilité critique CVE-2024-21762 affectant le VPN SSL de FortiOS. Cette vulnérabilité...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-004/
Date : Fri, 09 Feb 2024 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Microsoft Outlook (15 février 2024)
Description: \[Mise à jour du 15 mars 2024\] Ajout de précision concernant les défi-réponses NTLM \[Mise à jour du 22 février 2024\] Ajout de recommandations et de précisions sur le fonctionnement de la vulnérabilité. La vulnérabilité CVE-2024-21413 permet à un attaquant de contourner les mesures de sécurité...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-005/
Date : Thu, 15 Feb 2024 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Palo Alto Networks GlobalProtect (12 avril 2024)
Description: \[Mise à jour du 10 mai 2024\] Le CERT-FR est intervenu pour le traitement d'une compromission par rançongiciel au sein d'une entité française. Dans le cadre de cette attaque, la vulnérabilité a été exploitée pour ensuite réaliser une latéralisation dans le système d'information de la victime et...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-006/
Date : Fri, 12 Apr 2024 00:00:00 +0000
Titre : Multiples vulnérabilités dans les produits Cisco (25 avril 2024)
Description: Le 24 avril 2024, Cisco a publié trois avis de sécurité concernant des vulnérabilités affectant les équipements de sécurité ASA et FTD. Deux d'entre eux concernent les vulnérabilités CVE-2024-20353 et CVE-2024-20359 qui sont activement exploitées dans le cadre d'attaques ciblées. La vulnérabilité...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-007/
Date : Thu, 25 Apr 2024 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans les produits Check Point  (30 mai 2024)
Description: [Mise à jour du 31 mai 2024] Des preuves de concept sont désormais disponibles publiquement sur Internet. De plus, l'éditeur indique avoir détecté des tentatives de compromission à partir du 7 avril 2024. **[Publication Initiale]** Une vulnérabilité a été découverte dans les produits Check Point....
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-008/
Date : Thu, 30 May 2024 00:00:00 +0000
Titre : Vulnérabilité dans OpenSSH (01 juillet 2024)
Description: Le 1 juillet 2024, OpenSSH a publié un avis de sécurité concernant la vulnérabilité critique CVE-2024-6387. Cette vulnérabilité permet à un attaquant non authentifié d'exécuter du code arbitraire à distance avec les privilèges *root*. L'éditeur précise que les versions 8.5p1 à 9.7p1 sont...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-009/
Date : Mon, 01 Jul 2024 00:00:00 +0000
Titre : Multiples vulnérabilités dans Roundcube (09 août 2024)
Description: Le 4 août 2024, Roundcube a publié des correctifs concernant les vulnérabilités critiques CVE-2024-42008 et CVE-2024-42009 affectant son serveur de courriel. Ces vulnérabilités permettent des injections de code indirectes à distance (XSS) qui peuvent, par exemple, conduire à la récupération du...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-010/
Date : Fri, 09 Aug 2024 00:00:00 +0000
Titre : Vulnérabilité dans SonicWall (10 septembre 2024)
Description: Le 22 août 2024, Sonicwall a publié un correctif concernant la vulnérabilité critique CVE-2024-40766 affectant les pare-feux Sonicwall génération 5, 6 et 7. Cette vulnérabilité, de type contrôle d'accès défaillant, permet à un attaquant de provoquer un déni de service à distance, une atteinte à...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-011/
Date : Tue, 10 Sep 2024 00:00:00 +0000
Titre : [MàJ] Vulnérabilités affectant OpenPrinting CUPS (27 septembre 2024)
Description: **[Mise à jour du 10 octobre 2024]** Le 28 septembre 2024, Elastic Security Labs a publié des règles de détection au format propriétaire de l'éditeur (cf. section Documentation), qui sont confirmées par les analyses du CERT-FR pour la détection des attaques connues. **[Publication initiale]** De...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-012/
Date : Fri, 27 Sep 2024 00:00:00 +0000
Titre : Exploitations de vulnérabilités dans Ivanti Cloud Services Appliance (CSA) (22 octobre 2024)
Description: Ivanti a publié plusieurs avis de sécurité sur des vulnérabilités affectant CSA qui sont activement exploitées : * le 10 septembre 2024, Ivanti a publié un avis de sécurité concernant la vulnérabilité CVE-2024-8190 qui permet à un attaquant, authentifié en tant qu'administrateur, d'exécuter du...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-013/
Date : Tue, 22 Oct 2024 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités dans Fortinet FortiManager (23 octobre 2024)
Description: **[Mise à jour du 14 janvier 2025]** **Publication des correctifs** Le 14 janvier 2025, Fortinet a publié un avis de sécurité relatif à la vulnérabilité CVE-2024-50566 qui correspond à la vulnérabilité de type jour-zéro pour laquelle une preuve de concept a été publiée en novembre 2024. Des...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-014/
Date : Wed, 23 Oct 2024 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités sur l'interface d'administration des équipements Palo Alto Networks (15 novembre 2024)
Description: Le 8 novembre 2024, Palo Alto Networks a publié un avis de sécurité relatif à une vulnérabilité critique dans certains pare-feux Palo Alto Networks. Elle permet à un attaquant non authentifié d'exécuter du code arbitraire à distance sur l'interface d'administration des équipements. L'éditeur...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-015/
Date : Fri, 15 Nov 2024 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans les produits Ivanti (09 janvier 2025)
Description: Une vulnérabilité jour-zéro de type débordement de pile a été découverte dans Ivanti Connect Secure (ICS), Policy Secure (IPS), Neurons for Zero Trust Access (ZTA) gateways. Cette vulnérabilité, d'identifiant CVE-2025-0282, permet à un attaquant non authentifié de provoquer une exécution de code...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-001/
Date : Thu, 09 Jan 2025 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans les produits Fortinet (14 janvier 2025)
Description: \[Mise à jour du 28 janvier 2025\] Une preuve de concept permettant l'exploitation de cette vulnérabilité est disponible publiquement. Le 14 janvier 2025, Fortinet a publié un avis de sécurité concernant la vulnérabilité critique CVE-2024-55591 affectant FortiOS et FortiProxy. Elle permet à un...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-002/
Date : Tue, 14 Jan 2025 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans les produits Ivanti (03 avril 2025)
Description: **\[Mise à jour du 11 avril 2025\]** Le CERT-FR a connaissance d'une preuve de concept publique permettant de provoquer une exécution de code arbitraire à distance. **[Mise à jour du 04 avril 2025]** Le CERT-FR a connaissance d'une preuve de concept publique permettant de provoquer un arrêt du...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-003/
Date : Thu, 03 Apr 2025 00:00:00 +0000
Titre : Activités de post-exploitation dans Fortinet FortiGate (11 avril 2025)
Description: Fortinet a publié le 10 avril 2025 un billet de blogue [1] indiquant l'utilisation d'une technique de post-exploitation qui permet une atteinte à la confidentialité des données de l'ensemble du système des équipements Fortigate affectés. Cette technique repose sur l'utilisation d'un lien...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-004/
Date : Fri, 11 Apr 2025 00:00:00 +0000
Titre : Vulnérabilité dans SAP NetWeaver (28 avril 2025)
Description: Le 24 avril 2025, SAP a publié un bulletin de sécurité relatif à la vulnérabilité CVE-2025-31324 qui permet l'exécution de code arbitraire à distance pour un utilisateur non authentifié. Cette vulnérabilité est provoquée par un contournement de la politique de sécurité qui permet de télécharger...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-005/
Date : Mon, 28 Apr 2025 00:00:00 +0000
Titre : Vulnérabilité dans les produits Fortinet (13 mai 2025)
Description: Le 13 mai 2025, Fortinet a publié un avis de sécurité concernant la vulnérabilité CVE-2025-32756. Celle-ci permet à un attaquant non authentifié d'exécuter du code arbitraire à distance. L'éditeur indique que cette vulnérabilité est activement exploitée. Les exploitations constatées jusqu'ici...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-006/
Date : Tue, 13 May 2025 00:00:00 +0000
Titre : Multiples vulnérabilités dans Ivanti Endpoint Manager Mobile (EPMM) (14 mai 2025)
Description: [Mise à jour du 15 mai 2025] Une preuve de concept est publiquement disponible sur Internet. [Publication initiale] Le 13 mai 2025, Ivanti a publié deux avis de sécurité concernant les vulnérabilités CVE-2025-4427 et CVE-2025-4428. L'utilisation combinée de ces deux vulnérabilités permet...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-007/
Date : Wed, 14 May 2025 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Roundcube (05 juin 2025)
Description: [Mise à jour du 06 juin 2025] Une preuve de concept est publiquement disponible. [Publication initiale] Le 01 juin 2025, Roundcube a publié des correctifs concernant une vulnérabilité critique affectant son portail de messagerie ainsi que tous les produits l'incluant (par exemple cPanel et...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-008/
Date : Thu, 05 Jun 2025 00:00:00 +0000
Titre : Multiples vulnérabilités dans Citrix NetScaler ADC et NetScaler Gateway (01 juillet 2025)
Description: **[Mise à jour du 17 juillet 2025]** L'éditeur a publié un lien contenant une méthode d'évaluation permettant d'identifier des tentatives d'exploitation dans les journaux applicatifs et systèmes [12]. **[Mise à jour du 7 juillet 2025]** Le 17 juin 2025, Citrix a publié un bulletin de sécurité...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-009/
Date : Tue, 01 Jul 2025 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités dans Microsoft SharePoint (21 juillet 2025)
Description: **[Mise à jour du 23 juillet 2025]** Le 20 juillet 2025, Microsoft a publié des correctifs pour une vulnérabilité de type limitation insuffisante d'un chemin d'accès à un répertoire restreint, aussi appelé *path traversal*, affectant SharePoint Enterprise Server 2016, SharePoint Server 2019 et...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-010/
Date : Mon, 21 Jul 2025 00:00:00 +0000
Titre : Incidents de sécurité dans les pare-feux SonicWall (05 août 2025)
Description: [Mise à jour du 7 août 2025] Le 6 août 2025, SonicWall a remplacé une partie de son communiqué initial pour indiquer que les incidents de sécurité évoqués étaient vraisemblablement corrélés à la vulnérabilité CVE-2024-40766. Celle-ci a fait l'objet d'un bulletin de sécurité, SNWLID-2024-0015 (cf....
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-011/
Date : Tue, 05 Aug 2025 00:00:00 +0000
Titre : Vulnérabilité dans Citrix NetScaler ADC et NetScaler Gateway (26 août 2025)
Description: Le 26 août 2025, Citrix a publié un bulletin de sécurité (cf. section Documentation) concernant, entre autres, la vulnérabilité CVE-2025-7775. Celle-ci permet une exécution de code arbitraire à distance et affecte toutes les versions de Citrix NetScaler ADC et NetScaler Gateway, dans certaines...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-012/
Date : Tue, 26 Aug 2025 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités dans Cisco ASA et FTD (25 septembre 2025)
Description: **[Mise à jour du 07 novembre 2025]** Le 5 novembre 2025, Cisco a mis a jour son billet de blogue initialement publié le 25 septembre 2025 (cf. section Documentation). L'éditeur déclare avoir connaissance d'une nouvelle attaque, affectant les équipements ASA et FTD vulnérables, qui cause un déni...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-013/
Date : Thu, 25 Sep 2025 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans React Server Components (05 décembre 2025)
Description: **[Mise à jour du 11 décembre 2025]** Le CERT-FR a connaissance de multiples exploitations de la vulnérabilité CVE-2025-55182. Les serveurs avec une version vulnérable exposés après la publication des preuves de concept publiques du 5 décembre 2025 doivent être considérés comme compromis....
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2025-ALE-014/
Date : Fri, 05 Dec 2025 00:00:00 +0000
Titre : [MàJ] Multiples vulnérabilités dans Ivanti Endpoint Manager Mobile (30 janvier 2026)
Description: [Mise à jour du 09 février 2026] Le 6 février 2026, Ivanti a mis à disposition des scripts RPM de détection d'indicateurs de compromission, à utiliser en fonction de la version d'EPMM installée. L'éditeur a également mis son guide d'analyse à jour (cf. section Documentation). [Mise à jour du 02...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2026-ALE-001/
Date : Fri, 30 Jan 2026 00:00:00 +0000
Titre : [MàJ] Vulnérabilité dans Cisco Catalyst SD-WAN (25 février 2026)
Description: Une vulnérabilité a été découverte dans Cisco Catalyst SD-WAN. Elle permet à un attaquant de provoquer un contournement de la politique de sécurité. Cisco indique que la vulnérabilité CVE-2026-20127 est activement exploitée.
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2026-ALE-002/
Date : Wed, 25 Feb 2026 00:00:00 +0000
Titre : Note d’alerte – Ciblage des messageries instantanées (20 mars 2026)
Description: Les travaux conjoints des services membres du **Centre de Coordination des Crises Cyber (C4)** ont permis d’identifier une recrudescence de campagnes d’attaques ciblant les comptes de messagerie instantanées. Ces campagnes ciblent particulièrement les secteurs régaliens (personnalités politiques,...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2026-ALE-003/
Date : Fri, 20 Mar 2026 00:00:00 +0000
Titre : Vulnérabilité dans F5 BIG-IP Access Policy Manager (31 mars 2026)
Description: Le 15 octobre 2025, F5 a publié un avis de sécurité concernant entre autres la vulnérabilité CVE-2025-53521. Celle-ci affecte BIG-IP APM et permet à un attaquant non authentifié d'exécuter du code à distance. Le 29 mars 2026, l'éditeur indique que cette vulnérabilité est exploitée activement. Le...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2026-ALE-004/
Date : Tue, 31 Mar 2026 00:00:00 +0000
Titre : [Màj] Vulnérabilité dans Microsoft Exchange Server (15 mai 2026)
Description: [Mise à jour du 11 juin 2026] Le 9 juin 2026, Microsoft a publié des versions correctives. [Publication initiale] Le 14 mai 2026, Microsoft a publié un avis de sécurité concernant la vulnérabilité CVE-2026-42897 affectant Exchange Server. Elle permet à un attaquant non authentifié de provoquer...
Lien : https://www.cert.ssi.gouv.fr/alerte/CERTFR-2026-ALE-005/
Date : Fri, 15 May 2026 00:00:00 +0000
Titre : Vulnérabilité dans Cisco Catalyst SD-WAN (05 juin 2026)
Description: Une vulnérabilité a été découverte dans Cisco Catalyst SD-WAN. Elle permet à un attaquant de provoquer une élévation de privilèges. Cisco indique que la vulnérabilité CVE-2026-20245 est activement exploitée.
Lien : https://www.cert.ssi.gouv.fr/avis/CERTFR-2026-AVI-0699/
Date : Fri, 05 Jun 2026 00:00:00 +0000

# Étape 2 : Extraction des CVE

In [2]:
import requests
import re


cve_list_avis = []

# liste de dictionnaire pour le dataframe
list_cve = []
#url = "https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-001/json/"
for entry in rss_avis_feed.entries:
    link_array = entry.link.split("/")
    # example split :
    #['https:', '', 'www.cert.ssi.gouv.fr', 'avis', 'CERTFR-2026-AVI-0701', '']
    bulletin_name = link_array[4]
    url = "https://www.cert.ssi.gouv.fr/avis/" + bulletin_name +"/json/"
    #print(url)

    response = requests.get(url)
    data = response.json()
    for cve_item in data.get("cves", []):
            cve_id = cve_item.get("name")

            cve_data = {
                "ID ANSSI": bulletin_name,
                "Titre ANSSI": data.get("title"),
                "Type": "Avis",
                "Date": data.get("date"),
                "CVE": cve_id,
                "CVSS": None,
                "Base Severity": None,
                "CWE": None,
                "EPSS": None,
                "Lien": cve_item.get("url"),
                "Description": data.get("description"),
                "Editeur": None,
                "Produit": None,
                "Versions affectées": None
            }
            list_cve.append(cve_data)


    #Extraction des CVE reference dans la clé cves du dict data
    ref_cves=list(data["cves"])
    #attention il s’agit d’une liste des dictionnaires avec name et url comme clés
    # print( "CVE référencés ", ref_cves)
    # Extraction des CVE avec une regex
    cve_pattern = r"CVE-\d{4}-\d{4,7}"
    cve_list_avis.append(list(set(re.findall(cve_pattern, str(data)))))


cve_list_alert = []
for entry in rss_alerte_feed.entries:
    link_array = entry.link.split("/")
    # example split :
    #['https:', '', 'www.cert.ssi.gouv.fr', 'avis', 'CERTFR-2026-AVI-0701', '']
    bulletin_name = link_array[4]
    url = "https://www.cert.ssi.gouv.fr/alerte/" + bulletin_name +"/json/"
    # print(url)

    response = requests.get(url)
    data = response.json()
    for cve_item in data.get("cves", []):
            cve_id = cve_item.get("name")

            cve_data = {
                "ID ANSSI": data.get("reference"),
                "Titre ANSSI": data.get("title"),
                "Type": "Alerte",
                "Date": data.get("date"),
                "CVE": cve_id,
                "CVSS": None,
                "Base Severity": None,
                "CWE": None,
                "EPSS": None,
                "Lien": cve_item.get("url"),
                "Description": data.get("description"),
                "Editeur": None,        #
                "Produit": None,
                "Versions affectées": None
            }
            list_cve.append(cve_data)
    #Extraction des CVE reference dans la clé cves du dict data
    ref_cves=list(data["cves"])
    #attention il s’agit d’une liste des dictionnaires avec name et url comme clés
    # print( "CVE référencés ", ref_cves)
    # Extraction des CVE avec une regex
    cve_pattern = r"CVE-\d{4}-\d{4,7}"
    cve_list_alert.append(list(set(re.findall(cve_pattern, str(data)))))

print(list_cve)

[{'ID ANSSI': 'CERTFR-2026-AVI-0699', 'Titre ANSSI': 'Vulnérabilité dans Cisco Catalyst SD-WAN', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-20245', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-20245', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0711', 'Titre ANSSI': 'Multiples vulnérabilités dans les VPN Check Point', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-50752', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-50752', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0711', 'Titre ANSSI': 'Multiples vulnérabilités dans les VPN Check Point', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-50751', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-50751', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0712', 'Titre ANSSI': 'Vulnérabilité dans Veeam Backup & Replication', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44963', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44963', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0713', 'Titre ANSSI': 'Vulnérabilité dans les produits Schneider Electric EcoStruxure IT Data Center Expert', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-8045', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-8045', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0714', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Siemens', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2025-15467', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2025-15467', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0714', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Siemens', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-24349', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-24349', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0714', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Siemens', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2025-40808', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2025-40808', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44746', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44746', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44750', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44750', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44743', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44743', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44755', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44755', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44754', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44754', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-29145', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-29145', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44751', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44751', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44757', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44757', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-27671', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-27671', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44744', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44744', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-44748', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-44748', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2025-68161', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2025-68161', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-24315', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-24315', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-22732', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-22732', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0715', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits SAP', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-40128', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-40128', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-34180', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-34180', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-35188', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-35188', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42766', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42766', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-9076', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-9076', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-34181', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-34181', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42770', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42770', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-45445', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-45445', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-7383', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-7383', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42771', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42771', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42765', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42765', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42769', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42769', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-45447', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-45447', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-45446', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-45446', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-34183', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-34183', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42767', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42767', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42764', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42764', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-42768', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-42768', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0717', 'Titre ANSSI': 'Multiples vulnérabilités dans OpenSSL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-34182', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-34182', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0718', 'Titre ANSSI': 'Vulnérabilité dans PostgreSQL', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-9617', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-9617', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41716', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41716', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-40993', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-40993', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41717', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41717', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41721', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41721', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41695', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41695', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41729', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41729', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41719', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41719', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41697', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41697', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41008', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41008', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41694', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41694', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41696', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41696', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-41711', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-41711', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités dans les produits Spring', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-40988', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-40988', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}, {'ID ANSSI': 'CERTFR-2026-AVI-0719', 'Titre ANSSI': 'Multiples vulnérabilités 

In [3]:
print("CVE trouvés alerte:", cve_list_alert)
print("CVE trouvés avis", cve_list_avis)

CVE trouvés alerte: [['CVE-2023-37580'], ['CVE-2023-3519'], ['CVE-2023-42115', 'CVE-2023-42114', 'CVE-2023-42117', 'CVE-2023-42116', 'CVE-2023-42119', 'CVE-2023-42118'], ['CVE-2023-20198', 'CVE-2023-20273'], ['CVE-2023-4966'], ['CVE-2023-50164'], ['CVE-2024-21887', 'CVE-2024-22024', 'CVE-2024-21893', 'CVE-2024-21888', 'CVE-2023-46805'], ['CVE-2024-0402', 'CVE-2023-7028'], [], ['CVE-2024-21762'], ['CVE-2024-21413'], ['CVE-2024-3400'], ['CVE-2024-20353', 'CVE-2024-20359'], ['CVE-2024-24919'], ['CVE-2024-6387'], ['CVE-2024-42009', 'CVE-2024-42008', 'CVE-2024-42010'], ['CVE-2024-40766'], ['CVE-2024-47175', 'CVE-2024-47076', 'CVE-2024-47177', 'CVE-2024-47176'], ['CVE-2024-9380', 'CVE-2024-8963', 'CVE-2024-8190', 'CVE-2024-9379', 'CVE-2024-9381'], ['CVE-2024-50566', 'CVE-2024-47575'], ['CVE-2024-9474', 'CVE-2024-0012'], ['CVE-2025-0282', 'CVE-2025-0283'], ['CVE-2024-55591'], ['CVE-2025-0282', 'CVE-2025-22457'], ['CVE-2023-27997', 'CVE-2024-21762', 'CVE-2022-42475'], ['CVE-2025-31324'], ['CVE-2025-32756'], ['CVE-2025-4428', 'CVE-2025-4427'], ['CVE-2025-49113'], ['CVE-2025-5777', 'CVE-2025-6543'], ['CVE-2025-53771', 'CVE-2025-53770'], ['CVE-2024-40766'], ['CVE-2025-7775'], ['CVE-2025-20333', 'CVE-2025-20362'], ['CVE-2025-55182', 'CVE-2025-66478'], ['CVE-2026-1281', 'CVE-2026-1340'], ['CVE-2022-20775', 'CVE-2026-20127'], [], ['CVE-2025-53521'], ['CVE-2026-42897']]

In [4]:
import itertools

list_cve_id = list(itertools.chain.from_iterable(cve_list_alert)) + list(itertools.chain.from_iterable(cve_list_avis))
print(list_cve_id)

['CVE-2023-37580', 'CVE-2023-3519', 'CVE-2023-42119', 'CVE-2023-42118', 'CVE-2023-42115', 'CVE-2023-42116', 'CVE-2023-42114', 'CVE-2023-42117', 'CVE-2023-20198', 'CVE-2023-20273', 'CVE-2023-4966', 'CVE-2023-50164', 'CVE-2024-21893', 'CVE-2024-22024', 'CVE-2024-21888', 'CVE-2023-46805', 'CVE-2024-21887', 'CVE-2023-7028', 'CVE-2024-0402', 'CVE-2024-21762', 'CVE-2024-21413', 'CVE-2024-3400', 'CVE-2024-20359', 'CVE-2024-20353', 'CVE-2024-24919', 'CVE-2024-6387', 'CVE-2024-42008', 'CVE-2024-42010', 'CVE-2024-42009', 'CVE-2024-40766', 'CVE-2024-47076', 'CVE-2024-47176', 'CVE-2024-47177', 'CVE-2024-47175', 'CVE-2024-8190', 'CVE-2024-9379', 'CVE-2024-9381', 'CVE-2024-8963', 'CVE-2024-9380', 'CVE-2024-50566', 'CVE-2024-47575', 'CVE-2024-9474', 'CVE-2024-0012', 'CVE-2025-0282', 'CVE-2025-0283', 'CVE-2024-55591', 'CVE-2025-22457', 'CVE-2025-0282', 'CVE-2023-27997', 'CVE-2022-42475', 'CVE-2024-21762', 'CVE-2025-31324', 'CVE-2025-32756', 'CVE-2025-4427', 'CVE-2025-4428', 'CVE-2025-49113', 'CVE-2025-5777', 'CVE-2025-6543', 'CVE-2025-53770', 'CVE-2025-53771', 'CVE-2024-40766', 'CVE-2025-7775', 'CVE-2025-20362', 'CVE-2025-20333', 'CVE-2025-55182', 'CVE-2025-66478', 'CVE-2026-1281', 'CVE-2026-1340', 'CVE-2022-20775', 'CVE-2026-20127', 'CVE-2025-53521', 'CVE-2026-42897', 'CVE-2026-20245', 'CVE-2026-44119', 'CVE-2026-42535', 'CVE-2026-49975', 'CVE-2026-29170', 'CVE-2026-34355', 'CVE-2026-44631', 'CVE-2026-42536', 'CVE-2026-43951', 'CVE-2026-44186', 'CVE-2026-34356', 'CVE-2026-29167', 'CVE-2026-44185', 'CVE-2026-48913', 'CVE-2026-50751', 'CVE-2026-50752', 'CVE-2026-44963', 'CVE-2026-8045', 'CVE-2025-40808', 'CVE-2025-15467', 'CVE-2026-24349', 'CVE-2026-29145', 'CVE-2026-44755', 'CVE-2026-44746', 'CVE-2025-68161', 'CVE-2026-44743', 'CVE-2026-24315', 'CVE-2026-40128', 'CVE-2026-44744', 'CVE-2026-22732', 'CVE-2026-44751', 'CVE-2026-44748', 'CVE-2026-44750', 'CVE-2026-44754', 'CVE-2026-27671', 'CVE-2026-44757', 'CVE-2026-42770', 'CVE-2026-42767', 'CVE-2026-42769', 'CVE-2026-34181', 'CVE-2026-45445', 'CVE-2026-7383', 'CVE-2026-34182', 'CVE-2026-42765', 'CVE-2026-9076', 'CVE-2026-35188', 'CVE-2026-42766', 'CVE-2026-42771', 'CVE-2026-34183', 'CVE-2026-42764', 'CVE-2026-45447', 'CVE-2026-34180', 'CVE-2026-42768', 'CVE-2026-45446', 'CVE-2026-9617', 'CVE-2026-40993', 'CVE-2026-41695', 'CVE-2026-40988', 'CVE-2026-41729', 'CVE-2026-41697', 'CVE-2026-41008', 'CVE-2026-41003', 'CVE-2026-41711', 'CVE-2026-41721', 'CVE-2026-41716', 'CVE-2026-41719', 'CVE-2026-41701', 'CVE-2026-41717', 'CVE-2026-41696', 'CVE-2026-41694', 'CVE-2026-47913', 'CVE-2026-47911', 'CVE-2026-47912', 'CVE-2026-47916', 'CVE-2026-47952', 'CVE-2026-47930', 'CVE-2026-47933', 'CVE-2026-47914', 'CVE-2026-47925', 'CVE-2026-47918', 'CVE-2026-47920', 'CVE-2026-47924', 'CVE-2026-47919', 'CVE-2026-47923', 'CVE-2026-47926', 'CVE-2026-47961', 'CVE-2026-47960', 'CVE-2026-47937', 'CVE-2026-47959', 'CVE-2026-47915', 'CVE-2026-47921', 'CVE-2026-47932', 'CVE-2026-47931', 'CVE-2026-47928', 'CVE-2026-47955', 'CVE-2026-47917', 'CVE-2026-47929', 'CVE-2026-42490', 'CVE-2026-42489', 'CVE-2026-42487', 'CVE-2025-10263', 'CVE-2026-42488', 'CVE-2026-49740', 'CVE-2026-47352', 'CVE-2026-47350', 'CVE-2026-47349', 'CVE-2026-49741', 'CVE-2026-49738', 'CVE-2026-49742', 'CVE-2026-11607', 'CVE-2026-47351', 'CVE-2026-47348', 'CVE-2026-31790', 'CVE-2026-10520', 'CVE-2026-10523', 'CVE-2026-10727', 'CVE-2026-6973', 'CVE-2026-25089', 'CVE-2025-67862', 'CVE-2026-49938', 'CVE-2026-11263', 'CVE-2026-11131', 'CVE-2026-11178', 'CVE-2026-10953', 'CVE-2026-11119', 'CVE-2026-10929', 'CVE-2026-11034', 'CVE-2026-11029', 'CVE-2026-11072', 'CVE-2026-11291', 'CVE-2026-10967', 'CVE-2026-11019', 'CVE-2026-10883', 'CVE-2026-11247', 'CVE-2026-10984', 'CVE-2026-11287', 'CVE-2026-11295', 'CVE-2026-11077', 'CVE-2026-11097', 'CVE-2026-11226', 'CVE-2026-11082', 'CVE-2026-11007', 'CVE-2026-11145', 'CVE-2026-11010', 'CVE-2026-11215', 'CVE-2026-11035', 'CVE-2026-11278', 'CVE-2026-11188', 'CVE-2026-11175', 'CVE-2026-10934', 'CVE-2026-11045', 'CVE-2026-11080', 'CVE-2026-11012', 'CVE-2026-11167', 'CVE-2026-11148', 'CVE-2026-11290', 'CVE-2026-10959', 'CVE-2026-11297', 'CVE-2026-11172', 'CVE-2026-11270', 'CVE-2026-10923', 'CVE-2026-11163', 'CVE-2026-11108', 'CVE-2026-11064', 'CVE-2026-10892', 'CVE-2026-11127', 'CVE-2026-11065', 'CVE-2026-44803', 'CVE-2026-44818', 'CVE-2026-47635', 'CVE-2026-45460', 'CVE-2026-45459', 'CVE-2026-45474', 'CVE-2026-45461', 'CVE-2026-45475', 'CVE-2026-45643', 'CVE-2026-45485', 'CVE-2026-45649', 'CVE-2026-45458', 'CVE-2026-44820', 'CVE-2026-45472', 'CVE-2026-45455', 'CVE-2026-44824', 'CVE-2026-45471', 'CVE-2026-45456', 'CVE-2026-47293', 'CVE-2026-45457', 'CVE-2026-44823', 'CVE-2026-45486', 'CVE-2026-44821', 'CVE-2026-44817', 'CVE-2026-45466', 'CVE-2026-45469', 'CVE-2026-44822', 'CVE-2026-45645', 'CVE-2026-45463', 'CVE-2026-44812', 'CVE-2026-44819', 'CVE-2026-33828', 'CVE-2026-47652', 'CVE-2026-48565', 'CVE-2026-49160', 'CVE-2026-44801', 'CVE-2026-42829', 'CVE-2026-45490', 'CVE-2026-45598', 'CVE-2026-48575', 'CVE-2026-48563', 'CVE-2026-45634', 'CVE-2026-45601', 'CVE-2026-45491', 'CVE-2026-42969', 'CVE-2026-44807', 'CVE-2026-48576', 'CVE-2026-42916', 'CVE-2026-34335', 'CVE-2026-42971', 'CVE-2026-42987', 'CVE-2026-42911', 'CVE-2026-50507', 'CVE-2026-44805', 'CVE-2026-42828', 'CVE-2026-48568', 'CVE-2026-42914', 'CVE-2026-44809', 'CVE-2026-44812', 'CVE-2026-45607', 'CVE-2026-44804', 'CVE-2026-42910', 'CVE-2026-45635', 'CVE-2026-45599', 'CVE-2026-42993', 'CVE-2026-45602', 'CVE-2026-41092', 'CVE-2026-42980', 'CVE-2026-45638', 'CVE-2026-8863', 'CVE-2026-44799', 'CVE-2026-42905', 'CVE-2026-45654', 'CVE-2026-42904', 'CVE-2026-42908', 'CVE-2026-47289', 'CVE-2026-45640', 'CVE-2026-45648', 'CVE-2026-48566', 'CVE-2026-45596', 'CVE-2026-45637', 'CVE-2026-48570', 'CVE-2026-42907', 'CVE-2026-48578', 'CVE-2026-44813', 'CVE-2026-44803', 'CVE-2026-45586', 'CVE-2026-45656', 'CVE-2026-45603', 'CVE-2026-45653', 'CVE-2026-47656', 'CVE-2026-44808', 'CVE-2026-47288', 'CVE-2026-42992', 'CVE-2026-45487', 'CVE-2026-42913', 'CVE-2026-42984', 'CVE-2026-42981', 'CVE-2026-47653', 'CVE-2026-44802', 'CVE-2026-48583', 'CVE-2026-42970', 'CVE-2026-45594', 'CVE-2026-41108', 'CVE-2026-45588', 'CVE-2026-42836', 'CVE-2026-42968', 'CVE-2026-42985', 'CVE-2026-42983', 'CVE-2026-44815', 'CVE-2026-42979', 'CVE-2026-45592', 'CVE-2026-42903', 'CVE-2026-45597', 'CVE-2026-47654', 'CVE-2026-50508', 'CVE-2026-47648', 'CVE-2026-42915', 'CVE-2026-45600', 'CVE-2026-45604', 'CVE-2026-45591', 'CVE-2026-44810', 'CVE-2026-45636', 'CVE-2026-42906', 'CVE-2026-42978', 'CVE-2026-42991', 'CVE-2026-47291', 'CVE-2026-45642', 'CVE-2026-44811', 'CVE-2026-42973', 'CVE-2026-45641', 'CVE-2026-45593', 'CVE-2026-48573', 'CVE-2026-48574', 'CVE-2026-42912', 'CVE-2026-45608', 'CVE-2026-42837', 'CVE-2026-42977', 'CVE-2026-45595', 'CVE-2026-45655', 'CVE-2026-40404', 'CVE-2026-42974', 'CVE-2026-45657', 'CVE-2026-40409', 'CVE-2026-42986', 'CVE-2025-10263', 'CVE-2026-42989', 'CVE-2026-45658', 'CVE-2026-42972', 'CVE-2026-45639', 'CVE-2026-45605', 'CVE-2026-45606', 'CVE-2026-44814', 'CVE-2026-42909', 'CVE-2026-45591', 'CVE-2026-45491', 'CVE-2026-47643', 'CVE-2026-32193', 'CVE-2026-41098', 'CVE-2026-45464', 'CVE-2026-46069', 'CVE-2026-45500', 'CVE-2026-45835', 'CVE-2026-46000', 'CVE-2026-45583', 'CVE-2026-46193', 'CVE-2026-46225', 'CVE-2026-46075', 'CVE-2026-46142', 'CVE-2026-50031', 'CVE-2026-46220', 'CVE-2026-46133', 'CVE-2026-46031', 'CVE-2026-45458', 'CVE-2026-46114', 'CVE-2026-45994', 'CVE-2026-46115', 'CVE-2026-46016', 'CVE-2026-47287', 'CVE-2026-46070', 'CVE-2026-46177', 'CVE-2026-45991', 'CVE-2026-45844', 'CVE-2026-46173', 'CVE-2026-47298', 'CVE-2026-45839', 'CVE-2026-48562', 'CVE-2026-46053', 'CVE-2026-46190', 'CVE-2026-46125', 'CVE-2026-46119', 'CVE-2026-45502', 'CVE-2026-46003', 'CVE-2026-46227', 'CVE-2026-46116', 'CVE-2026-45845', 'CVE-2026-46191', 'CVE-2026-42789', 'CVE-2026-45986', 'CVE-2026-46043', 'CVE-2026-46155', 'CVE-2026-46178', 'CVE-2026-48569', 'CVE-2026-43503', 'CVE-2026-46185', 'CVE-2026-45468', 'CVE-2026-39833', 'CVE-2026-45501', 'CVE-2026-46137', 'CVE-2026-44819', 'CVE-2026-46187', 'CVE-2026-45997', 'CVE-2026-45650', 'CVE-2026-46218', 'CVE-2026-46063', 'CVE-2026-46084', 'CVE-2026-45476', 'CVE-2026-45996', 'CVE-2026-45485', 'CVE-2026-46146', 'CVE-2026-46160', 'CVE-2026-47637', 'CVE-2026-46047', 'CVE-2026-46197', 'CVE-2026-46159', 'CVE-2026-46111', 'CVE-2026-46048', 'CVE-2026-46138', 'CVE-2026-45988', 'CVE-2026-46199', 'CVE-2026-48962', 'CVE-2026-46189', 'CVE-2026-46186', 'CVE-2026-46064', 'CVE-2026-46038', 'CVE-2026-40371', 'CVE-2026-46109', 'CVE-2026-46099', 'CVE-2026-46208', 'CVE-2026-45644', 'CVE-2026-46151', 'CVE-2026-46023', 'CVE-2026-42790', 'CVE-2026-46012', 'CVE-2026-46062', 'CVE-2026-47284', 'CVE-2026-46021', 'CVE-2026-48959', 'CVE-2026-40376', 'CVE-2026-46024', 'CVE-2026-33113', 'CVE-2026-46226', 'CVE-2026-45843', 'CVE-2026-46086', 'CVE-2026-46078', 'CVE-2025-15649', 'CVE-2026-46037', 'CVE-2026-46083', 'CVE-2026-50511', 'CVE-2026-46123', 'CVE-2026-46161', 'CVE-2026-47641', 'CVE-2026-46026', 'CVE-2026-45993', 'CVE-2026-46091', 'CVE-2026-47634', 'CVE-2026-46022', 'CVE-2026-45454', 'CVE-2026-46102', 'CVE-2026-45989', 'CVE-2026-46273', 'CVE-2026-46077', 'CVE-2026-46127', 'CVE-2026-46019', 'CVE-2026-50512', 'CVE-2026-49975', 'CVE-2026-49161', 'CVE-2026-46065', 'CVE-2026-46112', 'CVE-2026-47639', 'CVE-2026-46018', 'CVE-2026-47636', 'CVE-2026-46195', 'CVE-2026-46027', 'CVE-2026-46300', 'CVE-2026-46052', 'CVE-2026-46113', 'CVE-2026-46124', 'CVE-2026-46068', 'CVE-2026-46002', 'CVE-2026-46150', 'CVE-2026-46085', 'CVE-2026-46156', 'CVE-2026-47640', 'CVE-2026-46107', 'CVE-2026-46198', 'CVE-2026-46145', 'CVE-2026-46082', 'CVE-2026-46033', 'CVE-2026-46006', 'CVE-2026-46005', 'CVE-2026-48560', 'CVE-2026-46204', 'CVE-2026-46172', 'CVE-2026-42496', 'CVE-2026-46110', 'CVE-2026-42835', 'CVE-2026-46152', 'CVE-2026-46212', 'CVE-2026-46122', 'CVE-2026-42902', 'CVE-2026-45999', 'CVE-2026-45840', 'CVE-2026-46056', 'CVE-2026-46004', 'CVE-2026-46049', 'CVE-2026-46149', 'CVE-2026-46106', 'CVE-2026-46233', 'CVE-2026-46120', 'CVE-2026-46108', 'CVE-2026-45841', 'CVE-2026-46236', 'CVE-2026-46136', 'CVE-2026-45465', 'CVE-2026-46128', 'CVE-2026-46163', 'CVE-2026-46089', 'CVE-2026-46072', 'CVE-2026-46011', 'CVE-2026-46080', 'CVE-2026-47631', 'CVE-2026-46051', 'CVE-2026-45591', 'CVE-2026-46131', 'CVE-2026-45503', 'CVE-2026-46176', 'CVE-2026-46050', 'CVE-2026-46214', 'CVE-2026-45846', 'CVE-2026-46098', 'CVE-2026-46196', 'CVE-2026-46180', 'CVE-2026-46219', 'CVE-2026-46101', 'CVE-2026-46164', 'CVE-2026-45475', 'CVE-2026-46058', 'CVE-2026-45647', 'CVE-2026-45467', 'CVE-2026-45484', 'CVE-2026-45482', 'CVE-2026-46079', 'CVE-2026-46167', 'CVE-2026-45479', 'CVE-2026-46144', 'CVE-2026-46234', 'CVE-2026-50292', 'CVE-2026-46231', 'CVE-2026-46094', 'CVE-2026-46205', 'CVE-2026-45453', 'CVE-2026-44824', 'CVE-2026-47292', 'CVE-2026-45842', 'CVE-2026-46206', 'CVE-2026-46040', 'CVE-2026-46103', 'CVE-2026-45471', 'CVE-2026-46230', 'CVE-2026-45456', 'CVE-2026-47281', 'CVE-2026-46129', 'CVE-2026-46165', 'CVE-2026-46238', 'CVE-2026-44821', 'CVE-2026-46132', 'CVE-2026-45834', 'CVE-2026-26142', 'CVE-2026-45462', 'CVE-2026-45836', 'CVE-2026-45838', 'CVE-2026-46015', 'CVE-2026-45987', 'CVE-2026-45504', 'CVE-2026-45998', 'CVE-2026-46088', 'CVE-2026-47638', 'CVE-2026-46209', 'CVE-2026-45483', 'CVE-2026-45481', 'CVE-2026-46168', 'CVE-2026-46009', 'CVE-2026-46046', 'CVE-2026-46229', 'CVE-2026-49413', 'CVE-2026-45257', 'CVE-2026-9204', 'CVE-2026-6269', 'CVE-2026-6552', 'CVE-2026-3553', 'CVE-2026-10733', 'CVE-2026-6277', 'CVE-2026-8589', 'CVE-2026-9694', 'CVE-2026-7250', 'CVE-2026-6976', 'CVE-2026-10087', 'CVE-2026-1500', 'CVE-2026-10019', 'CVE-2026-8579', 'CVE-2026-9987', 'CVE-2026-8568', 'CVE-2026-9906', 'CVE-2026-8539', 'CVE-2026-9879', 'CVE-2026-9970', 'CVE-2026-8553', 'CVE-2026-9991', 'CVE-2026-8571', 'CVE-2026-8560', 'CVE-2026-9876', 'CVE-2026-8582', 'CVE-2026-9914', 'CVE-2026-9924', 'CVE-2026-8562', 'CVE-2026-8517', 'CVE-2026-8548', 'CVE-2026-8512', 'CVE-2026-9880', 'CVE-2026-9942', 'CVE-2026-9116', 'CVE-2026-8555', 'CVE-2026-9950', 'CVE-2026-9891', 'CVE-2026-9929', 'CVE-2026-9937', 'CVE-2026-0274', 'CVE-2026-8527', 'CVE-2026-9995', 'CVE-2026-10021', 'CVE-2026-8541', 'CVE-2026-8544', 'CVE-2026-0272', 'CVE-2026-9910', 'CVE-2026-9888', 'CVE-2026-9992', 'CVE-2026-9941', 'CVE-2026-9121', 'CVE-2026-9126', 'CVE-2026-9989', 'CVE-2026-9899', 'CVE-2026-9112', 'CVE-2026-8581', 'CVE-2026-8584', 'CVE-2026-9913', 'CVE-2026-8531', 'CVE-2026-8545', 'CVE-2026-8587', 'CVE-2026-8549', 'CVE-2026-9931', 'CVE-2026-9114', 'CVE-2026-0269', 'CVE-2026-9903', 'CVE-2026-9873', 'CVE-2026-8547', 'CVE-2026-9923', 'CVE-2026-9982', 'CVE-2026-8569', 'CVE-2026-9953', 'CVE-2026-9890', 'CVE-2026-9926', 'CVE-2026-9984', 'CVE-2026-9955', 'CVE-2026-8556', 'CVE-2026-8570', 'CVE-2026-8518', 'CVE-2026-10020', 'CVE-2026-9977', 'CVE-2026-9945', 'CVE-2026-8574', 'CVE-2026-9894', 'CVE-2026-10012', 'CVE-2026-8573', 'CVE-2026-9996', 'CVE-2026-9902', 'CVE-2026-0270', 'CVE-2026-9113', 'CVE-2026-9889', 'CVE-2026-8537', 'CVE-2026-9900', 'CVE-2026-9892', 'CVE-2026-9979', 'CVE-2026-8523', 'CVE-2026-9911', 'CVE-2026-9965', 'CVE-2026-8521', 'CVE-2026-9893', 'CVE-2026-9874', 'CVE-2026-9959', 'CVE-2026-9933', 'CVE-2026-9966', 'CVE-2026-9881', 'CVE-2026-10008', 'CVE-2026-8535', 'CVE-2026-8580', 'CVE-2026-9917', 'CVE-2026-9956', 'CVE-2026-10014', 'CVE-2026-9947', 'CVE-2026-8546', 'CVE-2026-9986', 'CVE-2026-9875', 'CVE-2026-10015', 'CVE-2026-8564', 'CVE-2026-10013', 'CVE-2026-9962', 'CVE-2026-9939', 'CVE-2026-9115', 'CVE-2026-10009', 'CVE-2026-8520', 'CVE-2026-8575', 'CVE-2026-9907', 'CVE-2026-9934', 'CVE-2026-9920', 'CVE-2026-8522', 'CVE-2026-9964', 'CVE-2026-8567', 'CVE-2026-9930', 'CVE-2026-9878', 'CVE-2026-10017', 'CVE-2026-9886', 'CVE-2026-10006', 'CVE-2026-9118', 'CVE-2026-9877', 'CVE-2026-9904', 'CVE-2026-9928', 'CVE-2026-9999', 'CVE-2026-8585', 'CVE-2026-9915', 'CVE-2026-8559', 'CVE-2026-9124', 'CVE-2026-9935', 'CVE-2026-9932', 'CVE-2026-8513', 'CVE-2026-8577', 'CVE-2026-8583', 'CVE-2026-9969', 'CVE-2026-8528', 'CVE-2026-9944', 'CVE-2026-9895', 'CVE-2026-8563', 'CVE-2026-8538', 'CVE-2026-8534', 'CVE-2026-9960', 'CVE-2026-9916', 'CVE-2026-10007', 'CVE-2026-8540', 'CVE-2026-8576', 'CVE-2026-9997', 'CVE-2026-8510', 'CVE-2026-9963', 'CVE-2026-10022', 'CVE-2026-10004', 'CVE-2026-8524', 'CVE-2026-10018', 'CVE-2026-8536', 'CVE-2026-8561', 'CVE-2026-9976', 'CVE-2026-0273', 'CVE-2026-8533', 'CVE-2026-9912', 'CVE-2026-9882', 'CVE-2026-9940', 'CVE-2026-8530', 'CVE-2026-9975', 'CVE-2026-8558', 'CVE-2026-9927', 'CVE-2026-9949', 'CVE-2026-9968', 'CVE-2026-10016', 'CVE-2026-8519', 'CVE-2026-9990', 'CVE-2026-9897', 'CVE-2026-9872', 'CVE-2026-8578', 'CVE-2026-9958', 'CVE-2026-8552', 'CVE-2026-9905', 'CVE-2026-9901', 'CVE-2026-10000', 'CVE-2026-9887', 'CVE-2026-9972', 'CVE-2026-10011', 'CVE-2026-8572', 'CVE-2026-8557', 'CVE-2026-9898', 'CVE-2026-8550', 'CVE-2026-8511', 'CVE-2026-8543', 'CVE-2026-9936', 'CVE-2026-9909', 'CVE-2026-9952', 'CVE-2026-9918', 'CVE-2026-9908', 'CVE-2026-8515', 'CVE-2026-9974', 'CVE-2026-9123', 'CVE-2026-10010', 'CVE-2026-8526', 'CVE-2026-0267', 'CVE-2026-9111', 'CVE-2026-9998', 'CVE-2026-9983', 'CVE-2026-9971', 'CVE-2026-8566', 'CVE-2026-9985', 'CVE-2026-8516', 'CVE-2026-9922', 'CVE-2026-9980', 'CVE-2026-9925', 'CVE-2026-10002', 'CVE-2026-0266', 'CVE-2026-10003', 'CVE-2026-8525', 'CVE-2026-9883', 'CVE-2026-0271', 'CVE-2026-9921', 'CVE-2026-8586', 'CVE-2026-9981', 'CVE-2026-8529', 'CVE-2026-10005', 'CVE-2026-9919', 'CVE-2026-9896', 'CVE-2026-9994', 'CVE-2026-9120', 'CVE-2026-9993', 'CVE-2026-9988', 'CVE-2026-9885', 'CVE-2026-9978', 'CVE-2026-8565', 'CVE-2026-10001', 'CVE-2026-8551', 'CVE-2026-9954', 'CVE-2026-9973', 'CVE-2026-8514', 'CVE-2026-9948', 'CVE-2026-8532', 'CVE-2026-9951', 'CVE-2026-9938', 'CVE-2026-9117', 'CVE-2026-9961', 'CVE-2026-8554', 'CVE-2026-0268', 'CVE-2026-8509', 'CVE-2026-9110', 'CVE-2026-9946', 'CVE-2026-9884', 'CVE-2026-9967', 'CVE-2026-9957', 'CVE-2026-8542', 'CVE-2026-9943', 'CVE-2026-9752', 'CVE-2026-9750', 'CVE-2026-9747', 'CVE-2026-9740', 'CVE-2026-9748', 'CVE-2026-9743', 'CVE-2026-9742', 'CVE-2026-9753', 'CVE-2026-9754', 'CVE-2026-9741', 'CVE-2026-9751', 'CVE-2026-9735', 'CVE-2026-9746', 'CVE-2026-9749', 'CVE-2026-2004', 'CVE-2025-68146', 'CVE-2026-20257', 'CVE-2026-20256', 'CVE-2026-4358', 'CVE-2026-27448', 'CVE-2025-58181', 'CVE-2026-24051', 'CVE-2026-20253', 'CVE-2026-4147', 'CVE-2026-20260', 'CVE-2026-27459', 'CVE-2025-12818', 'CVE-2026-20251', 'CVE-2026-22701', 'CVE-2026-23490', 'CVE-2025-68121', 'CVE-2026-34520', 'CVE-2026-2006', 'CVE-2026-2005', 'CVE-2025-61732', 'CVE-2025-47913', 'CVE-2025-8869', 'CVE-2026-20258', 'CVE-2025-68161', 'CVE-2026-27142', 'CVE-2026-1229', 'CVE-2026-24049', 'CVE-2026-2003', 'CVE-2026-25679', 'CVE-2026-20254', 'CVE-2026-34516', 'CVE-2026-34477', 'CVE-2026-20255', 'CVE-2025-12817', 'CVE-2026-20259', 'CVE-2026-34480', 'CVE-2026-1703', 'CVE-2026-20252', 'CVE-2026-4148', 'CVE-2025-61731', 'CVE-2025-61726', 'CVE-2025-47914', 'CVE-2026-50258', 'CVE-2026-50259', 'CVE-2026-50262', 'CVE-2026-50261', 'CVE-2026-42015', 'CVE-2026-50260', 'CVE-2026-42013', 'CVE-2026-8829', 'CVE-2026-42012', 'CVE-2026-50257', 'CVE-2026-50256', 'CVE-2026-11332', 'CVE-2026-43958', 'CVE-2026-5419', 'CVE-2026-50263', 'CVE-2026-10879', 'CVE-2026-5260', 'CVE-2026-40997', 'CVE-2026-40994', 'CVE-2026-41862', 'CVE-2026-40999', 'CVE-2026-41000', 'CVE-2026-40987', 'CVE-2026-40995', 'CVE-2026-40992', 'CVE-2026-40996', 'CVE-2026-40985', 'CVE-2026-40986', 'CVE-2026-40998', 'CVE-2026-12020', 'CVE-2026-12007', 'CVE-2026-12019', 'CVE-2026-12008', 'CVE-2026-12034', 'CVE-2026-12026', 'CVE-2026-12025', 'CVE-2026-12011', 'CVE-2026-12032', 'CVE-2026-12010', 'CVE-2026-12033', 'CVE-2026-12031', 'CVE-2026-12012', 'CVE-2026-12015', 'CVE-2026-12030', 'CVE-2026-12009', 'CVE-2026-12029', 'CVE-2026-12016', 'CVE-2026-12013', 'CVE-2026-12027', 'CVE-2026-12018', 'CVE-2026-12017', 'CVE-2026-12022', 'CVE-2026-12028', 'CVE-2026-12023', 'CVE-2026-12014', 'CVE-2026-12035', 'CVE-2026-12024', 'CVE-2024-12905', 'CVE-2025-47907', 'CVE-2023-24531', 'CVE-2025-22870', 'CVE-2026-9266', 'CVE-2026-47825', 'CVE-2026-41708', 'CVE-2023-20585', 'CVE-2026-23437', 'CVE-2026-43234', 'CVE-2026-31758', 'CVE-2026-43126', 'CVE-2026-43012', 'CVE-2026-43206', 'CVE-2026-45970', 'CVE-2026-43328', 'CVE-2026-43333', 'CVE-2026-45852', 'CVE-2026-43009', 'CVE-2026-46300', 'CVE-2026-46113', 'CVE-2026-43325', 'CVE-2026-43437', 'CVE-2026-31575', 'CVE-2026-3150', 'CVE-2026-31729', 'CVE-2026-31736', 'CVE-2026-43501', 'CVE-2026-31607', 'CVE-2026-31473', 'CVE-2026-46114', 'CVE-2026-43037', 'CVE-2026-31406', 'CVE-2026-31685', 'CVE-2026-31405', 'CVE-2026-31493', 'CVE-2026-23380', 'CVE-2026-43499', 'CVE-2026-23359', 'CVE-2026-23243', 'CVE-2026-43190', 'CVE-2026-43112', 'CVE-2026-23317', 'CVE-2026-46110', 'CVE-2026-31614', 'CVE-2026-31516', 'CVE-2026-31483', 'CVE-2026-46021', 'CVE-2026-31464', 'CVE-2026-31402', 'CVE-2026-43252', 'CVE-2026-23271', 'CVE-2026-43362', 'CVE-2026-45843', 'CVE-2026-31613', 'CVE-2026-46004', 'CVE-2026-43338', 'CVE-2026-46333', 'CVE-2026-43054', 'CVE-2026-31480', 'CVE-2026-31629', 'CVE-2026-23444', 'CVE-2026-43361', 'CVE-2026-46043', 'CVE-2026-43359', 'CVE-2026-31521', 'CVE-2026-43013', 'CVE-2025-54518', 'CVE-2026-46243', 'CVE-2026-43503', 'CVE-2026-23274', 'CVE-2026-43284', 'CVE-2026-45910', 'CVE-2026-43360', 'CVE-2026-43341', 'CVE-2026-43414', 'CVE-2026-31568', 'CVE-2026-23140', 'CVE-2026-23062', 'CVE-2026-46000', 'CVE-2026-23204', 'CVE-2026-23139', 'CVE-2026-23187', 'CVE-2026-23198', 'CVE-2026-31504', 'CVE-2026-23213', 'CVE-2026-23214', 'CVE-2026-23107', 'CVE-2026-23095', 'CVE-2026-43500', 'CVE-2026-47334', 'CVE-2026-23094', 'CVE-2025-71199', 'CVE-2025-71224', 'CVE-2026-23102', 'CVE-2024-58097', 'CVE-2026-23096', 'CVE-2026-23141', 'CVE-2025-71195', 'CVE-2026-23164', 'CVE-2026-23006', 'CVE-2025-68725', 'CVE-2026-22991', 'CVE-2026-22984', 'CVE-2026-23083', 'CVE-2026-23113', 'CVE-2025-38591', 'CVE-2026-23128', 'CVE-2026-23054', 'CVE-2026-23093', 'CVE-2025-71268', 'CVE-2026-48681', 'CVE-2026-2

In [8]:
# Find duplicates
print(len(list_cve_id))
print(len(set(list_cve_id)))

1364
1318

In [9]:
list_cve_id = list(set(list_cve_id))
print(len(list_cve_id))

1318

# Étape 3 : Enrichissement des CVE

In [13]:
"""
READ ME !!!!

Cette cellule met 15 min à terminer. Elle crée un dictionnaire utilisé après.
Ce dictionnaire est déjà présent dans le fichier 'cve_info.json'.
Vous pouvez regarder les cellules suivantes pour le charger
"""
def cellule_not_to_lauch(cve_list):
    cve_info = {}
    for cve_id in cve_list:
        cve_info[cve_id] = {}
        url = (f"https://cveawg.mitre.org/api/cve/{cve_id}")
        response = requests.get(url)
        data = response.json()
        cvss_score = "na"

        # Extraire la description
        try:
            description = data["containers"]["cna"]["descriptions"][0]["value"]
        except:
            description = "na"
            continue
        # Extraire le score CVSS
        #ATTENTION tous les CVE ne contiennent pas nécessairement ce champ, gérez l’exception,
        #ou peut etre au lieu de cvssV3_0 c’est cvssV3_1 ou autre clé

        try:
            # print(data["containers"]["cna"]["metrics"][0])
            if list(data["containers"]["cna"]["metrics"][0].keys())[0] == 'format':
                key = list(data["containers"]["cna"]["metrics"][0].keys())[2]
            else:
                key = list(data["containers"]["cna"]["metrics"][0].keys())[0]

        except:
            pass
            # print("no metrics")

        try:
            cvss_score = data["containers"]["cna"]["metrics"][0][key]["baseScore"]
            # print("found")
        except Exception:
            pass
            # print("not found")

        cwe = "na"
        cwe_desc="na"
        try :
            problemtype = data["containers"]["cna"].get("problemTypes", {})
            if problemtype and "descriptions" in problemtype[0]:
                cwe = problemtype[0]["descriptions"][0].get("cweId", "Non disponible")
                cwe_desc=problemtype[0]["descriptions"][0].get("description", "Non disponible")
        except :
            pass

        # Extraire les produits affectés
        products = []
        try:
            affected = data["containers"]["cna"]["affected"]
            for product in affected:
                try:
                    vendor = product["vendor"]
                    product_name = product["product"]
                    versions = [v["version"] for v in product["versions"] if v["status"] == "affected"]
                    products.append([vendor, product_name, versions])
                except:
                    print(f"version error {cve_id}")
                # print(f"Éditeur : {vendor}, Produit : {product_name}, Versions : {', '.join(versions)}")
        except:
            pass

        cve_info[cve_id]['cvss_score'] = cvss_score
        cve_info[cve_id]['cwe'] = cwe
        cve_info[cve_id]['edition'] = product
        cve_info[cve_id]['description'] = description
        # Afficher les résultats
        # print(f"CVE : {cve_id}")
        # print(f"Description : {description}")
        # print(f"Score CVSS : {cvss_score}")
        # print(f"Type CWE : {cwe}")
        # print(f"CWE Description : {cwe_desc}")
        # print("END CVE\n\n\n")

    return cve_info


"""
Ne pas lancer sauf si c'est vraiment nécessaire
"""
# cve_info = cellule_not_to_lauch(cve_list)

version error CVE-2026-50261
version error CVE-2026-50261
version error CVE-2026-50261
version error CVE-2026-50261
version error CVE-2026-50261
version error CVE-2026-50261
version error CVE-2026-50261
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2024-6387
version error CVE-2026-50257
version error CVE-2026-50257
version error CVE-2026-50257
version error CVE-2026-50257
version error CVE-2026-50257
version error CVE-2026-50257
version error CVE-2026-50257
version error CVE-2026-43958
version error CVE-2026-43958
version error CVE-2026-43958
version error CVE-2026-43958
version error CVE-2026-43958
version error CVE-2026-42012
version error CVE-2026-42012
version error CVE-2026-42012
version error CVE-2026-42012
version error CVE-2024-12905
version error CVE-2026-50258
version error CVE-2026-50258
version error CVE-2026-50258
version error CVE-2026-50258
version error CVE-2026-50258
version error CVE-2026-50258
version error CVE-2026-50258
version error CVE-2026-5419
version error CVE-2026-5419
version error CVE-2026-5419
version error CVE-2026-5419
version error CVE-2026-5419
version error CVE-2026-50256
version error CVE-2026-50256
version error CVE-2026-50256
version error CVE-2026-50256
version error CVE-2026-50256
version error CVE-2026-50256
version error CVE-2026-50256
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-50263
version error CVE-2026-42015
version error CVE-2026-42015
version error CVE-2026-42015
version error CVE-2026-42015
version error CVE-2026-50259
version error CVE-2026-50259
version error CVE-2026-50259
version error CVE-2026-50259
version error CVE-2026-50259
version error CVE-2026-50259
version error CVE-2026-50259
version error CVE-2026-50262
version error CVE-2026-50262
version error CVE-2026-50262
version error CVE-2026-50262
version error CVE-2026-50262
version error CVE-2026-50262
version error CVE-2026-50262
version error CVE-2026-5260
version error CVE-2026-5260
version error CVE-2026-5260
version error CVE-2026-5260
version error CVE-2026-11332
version error CVE-2026-50260
version error CVE-2026-50260
version error CVE-2026-50260
version error CVE-2026-50260
version error CVE-2026-50260
version error CVE-2026-50260
version error CVE-2026-50260
version error CVE-2026-42013
version error CVE-2026-42013
version error CVE-2026-42013
version error CVE-2026-42013

In [12]:
cve_info

{'CVE-2026-8045': {'cvss_score': 7.1,
  'cwe': 'CWE-611',
  'edition': {'vendor': 'Schneider Electric',
   'product': 'EcoStruxure™ IT Data Center Expert',
   'versions': [{'status': 'affected', 'version': 'v9.1.1 and Prior'}],
   'defaultStatus': 'unaffected'}},
 'CVE-2026-41000': {'cvss_score': 3.7,
  'cwe': 'CWE-294',
  'edition': {'vendor': 'Spring',
   'product': 'Spring Web Services',
   'defaultStatus': 'unaffected',
   'versions': [{'status': 'affected',
     'version': '5.0.0',
     'lessThan': '5.0.2',
     'versionType': 'custom'},
    {'status': 'affected',
     'version': '4.1.0',
     'lessThan': '4.1.4',
     'versionType': 'custom'},
    {'status': 'affected',
     'version': '4.0.0',
     'lessThan': '4.0.19',
     'versionType': 'custom'},
    {'status': 'affected',
     'version': '3.1.0',
     'lessThan': '3.1.9',
     'versionType': 'custom'}]}},
 'CVE-2026-44801': {'cvss_score': 7.5,
  'cwe': 'CWE-416',
  'edition': {'vendor': 'Microsoft',
   'product': 'Windows Server 2025 (Server Core installation)',
   'platforms': ['x64-based Systems'],
   'versions': [{'version': '10.0.26100.0',
     'lessThan': '10.0.26100.32995',
     'versionType': 'custom',
     'status': 'affected'}]}},
 'CVE-2026-42829': {'cvss_score': 7.8,
  'cwe': 'CWE-284',
  'edition': {'vendor': 'Microsoft',
   'product': 'Windows 11 version 26H1',
   'platforms': ['ARM64-based Systems', 'x64-based Systems'],
   'versions': [{'version': '10.0.28000.0',
     'lessThan': '10.0.28000.2269',
     'versionType': 'custom',
     'status': 'affected'}]}},
 'CVE-2026-9876': {'cvss_score': 'not found',
  'cwe': 'CWE-416',
  'edition': {'vendor': 'Google',
   'product': 'Chrome',
   'versions': [{'version': '148.0.7778.216',
     'status': 'affected',
     'lessThan': '148.0.7778.216',
     'versionType': 'custom'}]}},
 'CVE-2026-8582': {'cvss_score': 'not found',
  'cwe': 'Non disponible',
  'edition': {'vendor': 'Google',
   'product': 'Chrome',
   'versions': [{'version': '148.0.7778.168',
     'status': 'affected',
     'lessThan': '148.0.7778.168',
     'versionType': 'custom'}]}},
 'CVE-2023-42114': {'cvss_score': 'not found',
  'cwe': 'CWE-125',
  'edition': {'vendor': 'Exim',
   'product': 'Exim',
   'versions': [{'version': 'exim 4.95', 'status': 'affected'}],
   'defaultStatus': 'unknown'}},
 'CVE-2026-43500': {'cvss_score': 7.8,
  'cwe': 'Non disponible',
  'edition': {'product': 'Linux',
   'vendor': 'Linux',
   'defaultStatus': 'affected',
   'repo': 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git',
   'programFiles': ['net/rxrpc/call_event.c', 'net/rxrpc/conn_event.c'],
   'versions': [{'version': '5.3', 'status': 'affected'},
    {'version': '0',
     'lessThan': '5.3',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.6.140',
     'lessThanOrEqual': '6.6.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.12.88',
     'lessThanOrEqual': '6.12.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.18.29',
     'lessThanOrEqual': '6.18.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '7.0.6',
     'lessThanOrEqual': '7.0.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '7.1-rc3',
     'lessThanOrEqual': '*',
     'status': 'unaffected',
     'versionType': 'original_commit_for_fix'}]}},
 'CVE-2026-9950': {'cvss_score': 'not found',
  'cwe': 'CWE-20',
  'edition': {'vendor': 'Google',
   'product': 'Chrome',
   'versions': [{'version': '148.0.7778.216',
     'status': 'affected',
     'lessThan': '148.0.7778.216',
     'versionType': 'custom'}]}},
 'CVE-2026-31483': {'cvss_score': 'not found',
  'cwe': 'Non disponible',
  'edition': {'product': 'Linux',
   'vendor': 'Linux',
   'defaultStatus': 'affected',
   'repo': 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git',
   'programFiles': ['arch/s390/kernel/syscall.c'],
   'versions': [{'version': '5.12', 'status': 'affected'},
    {'version': '0',
     'lessThan': '5.12',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '5.15.203',
     'lessThanOrEqual': '5.15.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.1.168',
     'lessThanOrEqual': '6.1.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.6.131',
     'lessThanOrEqual': '6.6.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.12.80',
     'lessThanOrEqual': '6.12.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.18.21',
     'lessThanOrEqual': '6.18.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.19.11',
     'lessThanOrEqual': '6.19.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '7.0',
     'lessThanOrEqual': '*',
     'status': 'unaffected',
     'versionType': 'original_commit_for_fix'}]}},
 'CVE-2026-47923': {'cvss_score': 5.5,
  'cwe': 'CWE-125',
  'edition': {'defaultStatus': 'affected',
   'product': 'Acrobat Reader',
   'vendor': 'Adobe',
   'versions': [{'lessThanOrEqual': '26.001.21651',
     'status': 'affected',
     'version': '0',
     'versionType': 'semver'}]}},
 'CVE-2026-8581': {'cvss_score': 'not found',
  'cwe': 'CWE-416',
  'edition': {'vendor': 'Google',
   'product': 'Chrome',
   'versions': [{'version': '148.0.7778.168',
     'status': 'affected',
     'lessThan': '148.0.7778.168',
     'versionType': 'custom'}]}},
 'CVE-2026-45986': {'cvss_score': 'not found',
  'cwe': 'Non disponible',
  'edition': {'product': 'Linux',
   'vendor': 'Linux',
   'defaultStatus': 'affected',
   'repo': 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git',
   'programFiles': ['drivers/crypto/ccree/cc_hash.c'],
   'versions': [{'version': '4.17', 'status': 'affected'},
    {'version': '0',
     'lessThan': '4.17',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '5.10.258',
     'lessThanOrEqual': '5.10.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '5.15.209',
     'lessThanOrEqual': '5.15.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.1.175',
     'lessThanOrEqual': '6.1.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.6.140',
     'lessThanOrEqual': '6.6.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.12.86',
     'lessThanOrEqual': '6.12.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '6.18.27',
     'lessThanOrEqual': '6.18.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '7.0.4',
     'lessThanOrEqual': '7.0.*',
     'status': 'unaffected',
     'versionType': 'semver'},
    {'version': '7.1-rc1',
     'lessThanOrEqual': '*',
     'status': 'unaffected',
     'versionType': 'original_commit_for_fix'}]}},
 'CVE-2026-9903': {'cvss_score': 'not found',
  'cwe': 'CWE-20',
  'edition': {'vendor': 'Google',
   'product': 'Chrome',
   'versions': [{'version': '148.0.7778.216',
     'status': 'affected',
     'lessThan': '148.0.7778.216',
     'versionType': 'custom'}]}},
 'CVE-2026-47328': {'cvss_score': 6.1,
  'cwe': 'CWE-590',
  'edition': {'vendor': 'Canonical',
   'product': 'Ubuntu Linux',
   'collectionURL': 'https://launchpad.net/ubuntu/+source/',
   'packageName': 'linux',
   'repo': 'https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/',
   'modules': ['AppArmor'],
   'versions': [{'status': 'affected',
     'version': '6.8.0',
     'lessThan': '6.8.0-124.124',
     'versionType': 'dpkg'},
    {'status': 'affected',
     'version': '6.17.0',
     'lessThan': '6.17.0-35.35',
     'versionType': 'dpkg'},
    {'status': 'affected',
     'version': '7.0.0',
     'lessThan': '7.0.0-22.22',
     'versionType': 'dpkg'}],
   'defaultStatus': 'unaffected'}},
 'CVE-2024-47575': {'cvss_score': 9.8,
  'cwe': 'CWE-306',
  'edition': {'vendor': 'Fortinet',
   'product': 'FortiManager',
   'cpes': ['cpe:2.3:o:fortinet:fortimanager:7.6.0:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.4.4:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.4.3:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.4.2:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.4.1:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.4.0:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.7:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.6:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.5:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.4:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.3:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.2:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.1:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.2.0:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.12:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.11:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.10:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.9:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.8:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.7:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.6:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.5:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.4:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.3:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.2:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.1:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:7.0.0:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.14:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.13:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.12:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.11:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.10:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.9:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.8:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.7:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.6:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.5:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.4:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.3:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.2:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.1:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.4.0:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.12:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.11:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.10:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.9:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.8:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.7:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.6:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.5:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.4:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.3:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.2:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.1:*:*:*:*:*:*:*',
    'cpe:2.3:o:fortinet:fortimanager:6.2.0:*:*:*:*:*:*:*'],
   'defaultStatus': 'unaffected',
   'versions': [{'version': '7.6.0', 'status': 'affected'},
    {'versionType': 'semver',
     'version': '7.4.0',
     'lessThanOrEqual': '7.4.4',
     'status': 'affected'},
    {'versionType': 'semver',
     'version': '7.2.0',
     'lessThanOrEqual': '7.2.7',
     'status': 'affected'},
    {'versionType': 'semver',
     'version': '7.0.0',
     'lessThanOrEqual': '7.0.12',
     'status': 'affected'},
    {'versionType': 'semver',
     'version': '6.4.0',
     'lessThanOrEqual': '6.4.14',
     'status': 'affected'},
    {'versionType': 'semver',
     'version': '6.2.0',
     'lessThanOrEqual': '6.2.12',
     'status': 'affected'}]}},
 'CVE-2023-20198': {'cvss_score': 10,
  'cwe': 'CWE-420',
  'edition': {'vendor': 'Cisco',
   'product': 'Cisco IOS XE Software',
   'versions': [{'version': '16.1.1', 'status': 'affected'},
    {'version': '16.1.2', 'status': 'affected'},
    {'version': '16.1.3', 'status': 'affected'},
    {'version': '16.2.1', 'status': 'affected'},
    {'version': '16.2.2', 'status': 'affected'},
    {'version': '16.3.1', 'status': 'affected'},
    {'version': '16.3.2', 'status': 'affected'},
    {'version': '16.3.3', 'status': 'affected'},
    {'version': '16.3.1a', 'status': 'affected'},
    {'version': '16.3.4', 'status': 'affected'},
    {'version': '16.3.5', 'status': 'affected'},
    {'version': '16.3.5b', 'status': 'affected'},
    {'version': '16.3.6', 'status': 'affected'},
    {'version': '16.3.7', 'status': 'affected'},
    {'version': '16.3.8', 'status': 'affected'},
    {'version': '16.3.9', 'status': 'affected'},
    {'version': '16.3.10', 'status': 'affected'},
    {'version': '16.3.11', 'status': 'affected'},
    {'version': '16.4.1', 'status': 'affected'},
    {'version': '16.4.2', 'status': 'affected'},
    {'version': '16.4.3', 'status': 'affected'},
    {'version': '16.5.1', 'status': 'affected'},
    {'version': '16.5.1a', 'status': 'affected'},
    {'version': '16.5.1b', 'status': 'affected'},
    {'version': '16.5.2', 'status': 'affected'},
    {'version': '16.5.3', 'status': 'affected'},
    {'version': '16.6.1', 'status': 'affected'},
    {'version': '16.6.2', 'status': 'affected'},
    {'version': '16.6.3', 'status': 'affected'},
    {'version': '16.6.4', 'status': 'affected'},
    {'version': '16.6.5', 'status': 'affected'},
    {'version': '16.6.4a', 'status': 'affected'},
    {'version': '16.6.5a', 'status': 'affected'},
    {'version': '16.6.6', 'status': 'affected'},
    {'version': '16.6.7', 'status': 'affected'},
    {'version': '16.6.8', 'status': 'affected'},
    {'version': '16.6.9', 'status': 'affected'},
    {'version': '16.6.10', 'status': 'affected'},
    {'version': '16.7.1', 'status': 'affected'},
    {'version': '16.7.1a', 'status': 'affected'},
    {'version': '16.7.1b', 'status': 'affected'},
    {'version': '16.7.2', 'status': 'affected'},
    {'version': '16.7.3', 'status': 'affected'},
    {'version': '16.7.4', 'status': 'affected'},
    {'version': '16.8.1', 'status': 'affected'},
    {'version': '16.8.1a', 'status': 'affected'},
    {'version': '16.8.1b', 'status': 'affected'},
    {'version': '16.8.1s', 'status': 'affected'},
    {'version': '16.8.1c', 'status': 'affected'},
    {'version': '16.8.1d', 'status': 'affected'},
    {'version': '16.8.2', 'status': 'affected'},
    {'version': '16.8.1e', 'status': 'affected'},
    {'version': '16.8.3', 'status': 'affected'},
    {'version': '16.9.1', 'status': 'affected'},
    {'version': '16.9.2', 'status': 'affected'},
    {'version': '16.9.1a', 'status': 'affected'},
    {'version': '16.9.1b', 'status': 'affected'},
    {'version': '16.9.1s', 'status': 'affected'},
    {'version': '16.9.3', 'status': 'affected'},
    {'version': '16.9.4', 'status': 'affected'},
    {'version': '16.9.3a', 'status': 'affected'},
    {'version': '16.9.5', 'status': 'affected'},
    {'version': '16.9.5f', 'status': 'affected'},
    {'version': '16.9.6', 'status': 'affected'},
    {'version': '16.9.7', 'status': 'affected'},
    {'version': '16.9.8', 'status': 'affected'},
    {'version': '16.10.1', 'status': 'affected'},
    {'version': '16.10.1a', 'status': 'affected'},
    {'version': '16.10.1b', 'status': 'affected'},
    {'version': '16.10.1s', 'status': 'affected'},
    {'version': '16.10.1c', 'status': 'affected'},
    {'version': '16.10.1e', 'status': 'affected'},
    {'version': '16.10.1d', 'status': 'affected'},
    {'version': '16.10.2', 'status': 'affected'},
    {'version': '16.10.1f', 'status': 'affected'},
    {'version': '16.10.1g', 'status': 'affected'},
    {'version': '16.10.3', 'status': 'affected'},
    {'version': '16.11.1', 'status': 'affected'},
    {'version': '16.11.1a', 'status': 'affected'},
    {'version': '16.11.1b', 'status': 'affected'},
    {'version': '16.11.2', 'status': 'affected'},
    {'version': '16.11.1s', 'status': 'affected'},
    {'version': '16.12.1', 'status': 'affected'},
    {'version': '16.12.1s', 'status': 'affected'},
    {'version': '16.12.1a', 'status': 'affected'},
    {'version': '16.12.1c', 'status': 'affected'},
    {'version': '16.12.1w', 'status': 'affected'},
    {'version': '16.12.2', 'status': 'affected'},
    {'version': '16.12.1y', 'status': 'affected'},
    {'version': '16.12.2a', 'status': 'affected'},
    {'version': '16.12.3', 'status': 'affected'},
    {'version': '16.12.8', 'status': 'affected'},
    {'version': '16.12.2s', 'status': 'affected'},
    {'version': '16.12.1x', 'status': 'affected'},
    {'version': '16.12.1t', 'status': 'affected'},
    {'version': '16.12.4', 'status': 'affected'},
    {'version': '16.12.3s', 'status': 'affected'},
    {'version': '16.12.3a', 'status': 'affected'},
    {'version': '16.12.4a', 'status': 'affected'},
    {'version': '16.12.5', 'status': 'affected'},
    {'version': '16.12.6', 'status': 'affected'},
    {'version': '16.12.1z1', 'status': 'affected'},
    {'version': '16.12.5a', 'status': 'affected'},
    {'version': '16.12.5b', 'status': 'affected'},
    {'version': '16.12.1z2', 'status': 'affected'},
    {'version': '16.12.6a', 'status': 'affected'},
    {'version': '16.12.7', 'status': 'affected'},
    {'version': '16.12.9', 'status': 'affected'},
    {'version': '16.12.10', 'status': 'affected'},
    {'version': '17.1.1', 'status': 'affected'},
    {'version': '17.1.1a', 'status': 'affected'},
    {'version': '17.1.1s', 'status': 'affected'},
    {'version': '17.1.1t', 'status': 'affected'},
    {'version': '17.1.3', 'status': 'affected'},
    {'version': '17.2.1', 'status': 'affected'},
    {'version': '17.2.1r', 'status': 'affected'},
    {'version': '17.2.1a', 'status': 'affected'},
    {'version': '17.2.1v', 'status': 'affected'},
    {'version': '17.2.2', 'status': 'affected'},
    {'version': '17.2.3', 'status': 'affected'},
    {'version': '17.3.1', 'status': 'affected'},
    {'version': '17.3.2', 'status': 'affected'},
    {'version': '17.3.3', 'status': 'affected'},
    {'version': '17.3.1a', 'status': 'affected'},
    {'version': '17.3.1w', 'status': 'affected'},
    {'version': '17.3.2a', 'status': 'affected'},
    {'version': '17.3.1x', 'status': 'affected'},
    {'version': '17.3.1z', 'status': 'affected'},
    {'version': '17.3.4', 'status': 'affected'},
    {'version': '17.3.5', 'status': 'affected'},
    {'version': '17.3.4a', 'status': 'affected'},
    {'version': '17.3.6', 'status': 'affected'},
    {'version': '17.3.4b', 'status': 'affected'},
    {'version': '17.3.4c', 'status': 'affected'},
    {'version': '17.3.5a', 'status': 'affected'},
    {'version': '17.3.5b', 'status': 'affected'},
    {'version': '17.3.7', 'status': 'affected'},
    {'version': '17.3.8', 'status': 'affected'},
    {'version': '17.4.1', 'status': 'affected'},
    {'version': '17.4.2', 'status': 'affected'},
    {'version': '17.4.1a', 'status': 'affected'},
    {'version': '17.4.1b', 'status': 'affected'},
    {'version': '17.4.2a', 'status': 'affected'},
    {'version': '17.5.1', 'status': 'affected'},
    {'version': '17.5.1a', 'status': 'affected'},
    {'version': '17.5.1b', 'status': 'affected'},
    {'version': '17.5.1c', 'status': 'affected'},
    {'version': '17.6.1', 'status': 'affected'},
    {'version': '17.6.2', 'status': 'affected'},
    {'version': '17.6.1w', 'status': 'affected'},
    {'version': '17.6.1a', 'status': 'affected'},
    {'version': '17.6.1x', 'status': 'affected'},
    {'version': '17.6.3', 'status': 'affected'},
    {'version': '17.6.1y', 'status': 'affected'},
    {'version': '17.6.1z', 'status': 'affected'},
    {'version': '17.6.3a', 'status': 'affected'},
    {'version': '17.6.4', 'status': 'affected'},

In [5]:

import json

def save_dict_to_json(data, filename):
    """Saves a dictionary to a JSON file."""
    with open(filename, 'w', encoding='utf-8') as f:
        # indent=4 makes the JSON file human-readable
        json.dump(data, f, indent=4, ensure_ascii=False)
    print(f"Data successfully saved to {filename}")

def load_json_to_dict(filename):
    """Loads a JSON file back into a Python dictionary."""
    with open(filename, 'r', encoding='utf-8') as f:
        return json.load(f)

In [16]:
#save the dictionary to a json to not launch again the cellule above
save_dict_to_json(cve_info, "cve_info.json")

Data successfully saved to cve_info.json

In [6]:
# Get the cve_info from the json file
cve_info = load_json_to_dict("cve_info.json")

In [10]:
print(cve_info['CVE-2026-22977'])

{'cvss_score': 'na', 'cwe': 'na', 'edition': {'product': 'Linux', 'vendor': 'Linux', 'defaultStatus': 'affected', 'repo': 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git', 'programFiles': ['net/core/sock.c'], 'versions': [{'version': '4.16', 'status': 'affected'}, {'version': '0', 'lessThan': '4.16', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '5.10.248', 'lessThanOrEqual': '5.10.*', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '5.15.198', 'lessThanOrEqual': '5.15.*', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '6.1.161', 'lessThanOrEqual': '6.1.*', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '6.6.121', 'lessThanOrEqual': '6.6.*', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '6.12.66', 'lessThanOrEqual': '6.12.*', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '6.18.6', 'lessThanOrEqual': '6.18.*', 'status': 'unaffected', 'versionType': 'semver'}, {'version': '6.19', 'lessThanOrEqual': '*', 'status': 'unaffected', 'versionType': 'original_commit_for_fix'}]}, 'description': "In the Linux kernel, the following vulnerability has been resolved:\n\nnet: sock: fix hardened usercopy panic in sock_recv_errqueue\n\nskbuff_fclone_cache was created without defining a usercopy region,\n[1] unlike skbuff_head_cache which properly whitelists the cb[] field.\n[2] This causes a usercopy BUG() when CONFIG_HARDENED_USERCOPY is\nenabled and the kernel attempts to copy sk_buff.cb data to userspace\nvia sock_recv_errqueue() -> put_cmsg().\n\nThe crash occurs when: 1. TCP allocates an skb using alloc_skb_fclone()\n   (from skbuff_fclone_cache) [1]\n2. The skb is cloned via skb_clone() using the pre-allocated fclone\n[3] 3. The cloned skb is queued to sk_error_queue for timestamp\nreporting 4. Userspace reads the error queue via recvmsg(MSG_ERRQUEUE)\n5. sock_recv_errqueue() calls put_cmsg() to copy serr->ee from skb->cb\n[4] 6. __check_heap_object() fails because skbuff_fclone_cache has no\n   usercopy whitelist [5]\n\nWhen cloned skbs allocated from skbuff_fclone_cache are used in the\nsocket error queue, accessing the sock_exterr_skb structure in skb->cb\nvia put_cmsg() triggers a usercopy hardening violation:\n\n[    5.379589] usercopy: Kernel memory exposure attempt detected from SLUB object 'skbuff_fclone_cache' (offset 296, size 16)!\n[    5.382796] kernel BUG at mm/usercopy.c:102!\n[    5.383923] Oops: invalid opcode: 0000 [#1] SMP KASAN NOPTI\n[    5.384903] CPU: 1 UID: 0 PID: 138 Comm: poc_put_cmsg Not tainted 6.12.57 #7\n[    5.384903] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.16.3-0-ga6ed6b701f0a-prebuilt.qemu.org 04/01/2014\n[    5.384903] RIP: 0010:usercopy_abort+0x6c/0x80\n[    5.384903] Code: 1a 86 51 48 c7 c2 40 15 1a 86 41 52 48 c7 c7 c0 15 1a 86 48 0f 45 d6 48 c7 c6 80 15 1a 86 48 89 c1 49 0f 45 f3 e8 84 27 88 ff <0f> 0b 490\n[    5.384903] RSP: 0018:ffffc900006f77a8 EFLAGS: 00010246\n[    5.384903] RAX: 000000000000006f RBX: ffff88800f0ad2a8 RCX: 1ffffffff0f72e74\n[    5.384903] RDX: 0000000000000000 RSI: 0000000000000004 RDI: ffffffff87b973a0\n[    5.384903] RBP: 0000000000000010 R08: 0000000000000000 R09: fffffbfff0f72e74\n[    5.384903] R10: 0000000000000003 R11: 79706f6372657375 R12: 0000000000000001\n[    5.384903] R13: ffff88800f0ad2b8 R14: ffffea00003c2b40 R15: ffffea00003c2b00\n[    5.384903] FS:  0000000011bc4380(0000) GS:ffff8880bf100000(0000) knlGS:0000000000000000\n[    5.384903] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033\n[    5.384903] CR2: 000056aa3b8e5fe4 CR3: 000000000ea26004 CR4: 0000000000770ef0\n[    5.384903] PKRU: 55555554\n[    5.384903] Call Trace:\n[    5.384903]  <TASK>\n[    5.384903]  __check_heap_object+0x9a/0xd0\n[    5.384903]  __check_object_size+0x46c/0x690\n[    5.384903]  put_cmsg+0x129/0x5e0\n[    5.384903]  sock_recv_errqueue+0x22f/0x380\n[    5.384903]  tls_sw_recvmsg+0x7ed/0x1960\n[    5.384903]  ? srso_alias_return_thunk+0x5/0xfbef5\n[    5.384903]  ? schedule+0x6d/0x270\n[    5.384903]  ? srso_alias_return_thunk+0x5/0xfbef5\n[    5.384903]  ? mutex_unlock+0x81/0xd0\n[    5.384903]  ? __pfx_mutex_unlock+0x10/0x10\n[    5.384903]  ? __pfx_tls_sw_recvmsg+0x10/0x10\n[    5.384903]  ? _raw_spin_lock_irqsave+0x8f/0xf0\n[    5.384903]  ? _raw_read_unlock_irqrestore+0x20/0x40\n[    5.384903]  ? srso_alias_return_thunk+0x5/0xfbef5\n\nThe crash offset 296 corresponds to skb2->cb within skbuff_fclones:\n  - sizeof(struct sk_buff) = 232 - offsetof(struct sk_buff, cb) = 40 -\n  offset of skb2.cb in fclones = 232 + 40 = 272 - crash offset 296 =\n  272 + 24 (inside sock_exterr_skb.ee)\n\nThis patch uses a local stack variable as a bounce buffer to avoid the hardened usercopy check failure.\n\n[1] https://elixir.bootlin.com/linux/v6.12.62/source/net/ipv4/tcp.c#L885\n[2] https://elixir.bootlin.com/linux/v6.12.62/source/net/core/skbuff.c#L5104\n[3] https://elixir.bootlin.com/linux/v6.12.62/source/net/core/skbuff.c#L5566\n[4] https://elixir.bootlin.com/linux/v6.12.62/source/net/core/skbuff.c#L5491\n[5] https://elixir.bootlin.com/linux/v6.12.62/source/mm/slub.c#L5719"}

In [8]:
print(list_cve[0])

{'ID ANSSI': 'CERTFR-2026-AVI-0699', 'Titre ANSSI': 'Vulnérabilité dans Cisco Catalyst SD-WAN', 'Type': 'Avis', 'Date': None, 'CVE': 'CVE-2026-20245', 'CVSS': None, 'Base Severity': None, 'CWE': None, 'EPSS': None, 'Lien': 'https://www.cve.org/CVERecord?id=CVE-2026-20245', 'Description': None, 'Editeur': None, 'Produit': None, 'Versions affectées': None}

In [12]:
for element in list_cve:
    cve_id = element['CVE']
    try:
        element['CVSS'] = cve_info[cve_id]['cvss_score']
        element['CWE'] = cve_info[cve_id]['cwe']
        element['Description'] = cve_info[cve_id]['description']
        element['Editeur'] = cve_info[cve_id]['edition']['vendor']
        element['Produit'] = cve_info[cve_id]['edition']['product']
        versions = []
        for version in cve_info[cve_id]['edition']['versions']:
            if version['status'] == 'affected':
                versions.append(version['version'])
        element['Versions affectées'] = versions
    except:
        print(f'{cve_id} not in the database')

CVE-2026-42489 not in the database
CVE-2026-42487 not in the database
CVE-2026-42488 not in the database
CVE-2026-42490 not in the database
CVE-2026-45257 not in the database
CVE-2026-49413 not in the database
CVE-2026-50261 not in the database
CVE-2026-50258 not in the database
CVE-2026-50257 not in the database
CVE-2026-5419 not in the database
CVE-2026-11332 not in the database
CVE-2026-42015 not in the database
CVE-2026-50263 not in the database
CVE-2026-50260 not in the database
CVE-2026-5260 not in the database
CVE-2026-50262 not in the database
CVE-2026-42013 not in the database
CVE-2026-50256 not in the database
CVE-2026-50259 not in the database
CVE-2026-43958 not in the database
CVE-2026-42012 not in the database
CVE-2026-41862 not in the database
CVE-2024-12905 not in the database
CVE-2026-47825 not in the database
CVE-2026-41708 not in the database
CVE-2026-35273 not in the database
CVE-2024-6387 not in the database
CVE-2024-47177 not in the database
CVE-2025-66478 not in the database

In [13]:
for cve in list_cve:
    cve_id = cve['CVE']
    url = f"https://api.first.org/data/v1/epss?cve={cve_id}"

    # Requête GET pour récupérer les données JSON
    response = requests.get(url)
    data = response.json()

    # Extraire le score EPSS
    epss_data = data.get("data", [])
    if epss_data:
        epss_score = epss_data[0]["epss"]
        print(f"CVE : {cve_id}")
        print(f"Score EPSS : {epss_score}")
        cve['EPSS'] = epss_score
    else:
        print(f"Aucun score EPSS trouvé pour {cve_id}")

CVE : CVE-2026-20245
Score EPSS : 0.003560000
CVE : CVE-2026-50752
Score EPSS : 0.000310000
CVE : CVE-2026-50751
Score EPSS : 0.118410000
CVE : CVE-2026-44963
Score EPSS : 0.005860000
CVE : CVE-2026-8045
Score EPSS : 0.000570000
CVE : CVE-2025-15467
Score EPSS : 0.028890000
CVE : CVE-2026-24349
Score EPSS : 0.000050000
CVE : CVE-2025-40808
Score EPSS : 0.000150000
CVE : CVE-2026-44746
Score EPSS : 0.000930000
CVE : CVE-2026-44750
Score EPSS : 0.000260000
CVE : CVE-2026-44743
Score EPSS : 0.000280000
CVE : CVE-2026-44755
Score EPSS : 0.000140000
CVE : CVE-2026-44754
Score EPSS : 0.000350000
CVE : CVE-2026-29145
Score EPSS : 0.000280000
CVE : CVE-2026-44751
Score EPSS : 0.000360000
CVE : CVE-2026-44757
Score EPSS : 0.000550000
CVE : CVE-2026-27671
Score EPSS : 0.000420000
CVE : CVE-2026-44744
Score EPSS : 0.000260000
CVE : CVE-2026-44748
Score EPSS : 0.000460000
CVE : CVE-2025-68161
Score EPSS : 0.000290000
CVE : CVE-2026-24315
Score EPSS : 0.000300000
CVE : CVE-2026-22732
Score EPSS : 0.000280000
CVE : CVE-2026-40128
Score EPSS : 0.001000000
CVE : CVE-2026-34180
Score EPSS : 0.000590000
CVE : CVE-2026-35188
Score EPSS : 0.000690000
CVE : CVE-2026-42766
Score EPSS : 0.000660000
CVE : CVE-2026-9076
Score EPSS : 0.000960000
CVE : CVE-2026-34181
Score EPSS : 0.000040000
CVE : CVE-2026-42770
Score EPSS : 0.000080000
CVE : CVE-2026-45445
Score EPSS : 0.000170000
CVE : CVE-2026-7383
Score EPSS : 0.000670000
CVE : CVE-2026-42771
Score EPSS : 0.000120000
CVE : CVE-2026-42765
Score EPSS : 0.000330000
CVE : CVE-2026-42769
Score EPSS : 0.000070000
CVE : CVE-2026-45447
Score EPSS : 0.000920000
CVE : CVE-2026-45446
Score EPSS : 0.000120000
CVE : CVE-2026-34183
Score EPSS : 0.000380000
CVE : CVE-2026-42767
Score EPSS : 0.000580000
CVE : CVE-2026-42764
Score EPSS : 0.000420000
CVE : CVE-2026-42768
Score EPSS : 0.000090000
CVE : CVE-2026-34182
Score EPSS : 0.000050000
CVE : CVE-2026-9617
Score EPSS : 0.000360000
CVE : CVE-2026-41716
Score EPSS : 0.000400000
CVE : CVE-2026-40993
Score EPSS : 0.000130000
CVE : CVE-2026-41717
Score EPSS : 0.000480000
CVE : CVE-2026-41721
Score EPSS : 0.002280000
CVE : CVE-2026-41695
Score EPSS : 0.000400000
CVE : CVE-2026-41729
Score EPSS : 0.000320000
CVE : CVE-2026-41719
Score EPSS : 0.000460000
CVE : CVE-2026-41697
Score EPSS : 0.000410000
CVE : CVE-2026-41008
Score EPSS : 0.000270000
CVE : CVE-2026-41694
Score EPSS : 0.000190000
CVE : CVE-2026-41696
Score EPSS : 0.000330000
CVE : CVE-2026-41711
Score EPSS : 0.000510000
CVE : CVE-2026-40988
Score EPSS : 0.000400000
CVE : CVE-2026-41003
Score EPSS : 0.000320000
CVE : CVE-2026-41701
Score EPSS : 0.000250000
CVE : CVE-2026-47916
Score EPSS : 0.000330000
CVE : CVE-2026-47933
Score EPSS : 0.000380000
CVE : CVE-2026-47925
Score EPSS : 0.000180000
CVE : CVE-2026-47931
Score EPSS : 0.000430000
CVE : CVE-2026-47921
Score EPSS : 0.000330000
CVE : CVE-2026-47926
Score EPSS : 0.000220000
CVE : CVE-2026-47919
Score EPSS : 0.000330000
CVE : CVE-2026-47911
Score EPSS : 0.000250000
CVE : CVE-2026-47932
Score EPSS : 0.000240000
CVE : CVE-2026-47930
Score EPSS : 0.000740000
CVE : CVE-2026-47912
Score EPSS : 0.000330000
CVE : CVE-2026-47915
Score EPSS : 0.000330000
CVE : CVE-2026-47960
Score EPSS : 0.001120000
CVE : CVE-2026-47955
Score EPSS : 0.000330000
CVE : CVE-2026-47929
Score EPSS : 0.000200000
CVE : CVE-2026-47923
Score EPSS : 0.000220000
CVE : CVE-2026-47937
Score EPSS : 0.000260000
CVE : CVE-2026-47928
Score EPSS : 0.000360000
CVE : CVE-2026-47961
Score EPSS : 0.000220000
CVE : CVE-2026-47959
Score EPSS : 0.000250000
CVE : CVE-2026-47914
Score EPSS : 0.000330000
CVE : CVE-2026-47924
Score EPSS : 0.000270000
CVE : CVE-2026-47917
Score EPSS : 0.000330000
CVE : CVE-2026-47918
Score EPSS : 0.000330000
CVE : CVE-2026-47913
Score EPSS : 0.000330000
CVE : CVE-2026-47920
Score EPSS : 0.000330000
CVE : CVE-2026-47952
Score EPSS : 0.000250000
Aucun score EPSS trouvé pour CVE-2026-42489
Aucun score EPSS trouvé pour CVE-2026-42487
CVE : CVE-2025-10263
Score EPSS : 0.000260000
Aucun score EPSS trouvé pour CVE-2026-42488
Aucun score EPSS trouvé pour CVE-2026-42490
CVE : CVE-2026-49742
Score EPSS : 0.000360000
CVE : CVE-2026-47350
Score EPSS : 0.000300000
CVE : CVE-2026-47349
Score EPSS : 0.000360000
CVE : CVE-2026-47351
Score EPSS : 0.000360000
CVE : CVE-2026-49738
Score EPSS : 0.000320000
CVE : CVE-2026-49741
Score EPSS : 0.000270000
CVE : CVE-2026-11607
Score EPSS : 0.000360000
CVE : CVE-2026-49740
Score EPSS : 0.002460000
CVE : CVE-2026-47352
Score EPSS : 0.000360000
CVE : CVE-2026-47348
Score EPSS : 0.000440000
CVE : CVE-2026-31790
Score EPSS : 0.000420000
CVE : CVE-2026-6973
Score EPSS : 0.059390000
CVE : CVE-2026-10523
Score EPSS : 0.090610000
CVE : CVE-2026-10520
Score EPSS : 0.479100000
CVE : CVE-2026-10727
Score EPSS : 0.004410000
CVE : CVE-2026-25089
Score EPSS : 0.008980000
CVE : CVE-2025-67862
Score EPSS : 0.000120000
CVE : CVE-2026-49938
Score EPSS : 0.000320000
CVE : CVE-2026-10892
Score EPSS : 0.001090000
CVE : CVE-2026-10967
Score EPSS : 0.000730000
CVE : CVE-2026-11175
Score EPSS : 0.000760000
CVE : CVE-2026-10923
Score EPSS : 0.000330000
CVE : CVE-2026-11108
Score EPSS : 0.000710000
CVE : CVE-2026-11007
Score EPSS : 0.000640000
CVE : CVE-2026-10883
Score EPSS : 0.000860000
CVE : CVE-2026-11290
Score EPSS : 0.000050000
CVE : CVE-2026-11263
Score EPSS : 0.000440000
CVE : CVE-2026-11226
Score EPSS : 0.000110000
CVE : CVE-2026-11127
Score EPSS : 0.000210000
CVE : CVE-2026-11291
Score EPSS : 0.000130000
CVE : CVE-2026-10953
Score EPSS : 0.001180000
CVE : CVE-2026-11119
Score EPSS : 0.001060000
CVE : CVE-2026-11019
Score EPSS : 0.000270000
CVE : CVE-2026-11188
Score EPSS : 0.000730000
CVE : CVE-2026-11045
Score EPSS : 0.000580000
CVE : CVE-2026-11034
Score EPSS : 0.000520000
CVE : CVE-2026-11080
Score EPSS : 0.000670000
CVE : CVE-2026-11163
Score EPSS : 0.000730000
CVE : CVE-2026-11247
Score EPSS : 0.000340000
CVE : CVE-2026-11029
Score EPSS : 0.001060000
CVE : CVE-2026-11167
Score EPSS : 0.000670000
CVE : CVE-2026-11010
Score EPSS : 0.001080000
CVE : CVE-2026-11215
Score EPSS : 0.000240000
CVE : CVE-2026-11065
Score EPSS : 0.001180000
CVE : CVE-2026-10929
Score EPSS : 0.000790000
CVE : CVE-2026-11131
Score EPSS : 0.000730000
CVE : CVE-2026-11148
Score EPSS : 0.000080000
CVE : CVE-2026-11297
Score EPSS : 0.000100000
CVE : CVE-2026-11082
Score EPSS : 0.000730000
CVE : CVE-2026-10959
Score EPSS : 0.000860000
CVE : CVE-2026-11172
Score EPSS : 0.000760000
CVE : CVE-2026-11077
Score EPSS : 0.000860000
CVE : CVE-2026-11278
Score EPSS : 0.000090000
CVE : CVE-2026-11178
Score EPSS : 0.000120000
CVE : CVE-2026-11064
Score EPSS : 0.000300000
CVE : CVE-2026-11295
Score EPSS : 0.000990000
CVE : CVE-2026-11012
Score EPSS : 0.001180000
CVE : CVE-2026-10934
Score EPSS : 0.000730000
CVE : CVE-2026-11270
Score EPSS : 0.000150000
CVE : CVE-2026-11072
Score EPSS : 0.000060000
CVE : CVE-2026-11145
Score EPSS : 0.000270000
CVE : CVE-2026-10984
Score EPSS : 0.000630000
CVE : CVE-2026-11287
Score EPSS : 0.000260000
CVE : CVE-2026-11097
Score EPSS : 0.000290000
CVE : CVE-2026-11035
Score EPSS : 0.000080000
CVE : CVE-2026-45457
Score EPSS : 0.000790000
CVE : CVE-2026-44803
Score EPSS : 0.001000000
CVE : CVE-2026-45472
Score EPSS : 0.000600000
CVE : CVE-2026-45463
Score EPSS : 0.000830000
CVE : CVE-2026-45645
Score EPSS : 0.000790000
CVE : CVE-2026-45649
Score EPSS : 0.000520000
CVE : CVE-2026-44812
Score EPSS : 0.001000000
CVE : CVE-2026-44822
Score EPSS : 0.000780000
CVE : CVE-2026-44817
Score EPSS : 0.001490000
CVE : CVE-2026-45474
Score EPSS : 0.000600000
CVE : CVE-2026-45643
Score EPSS : 0.000790000
CVE : CVE-2026-45461
Score EPSS : 0.000600000
CVE : CVE-2026-44823
Score EPSS : 0.001820000
CVE : CVE-2026-44820
Score EPSS : 0.000790000
CVE : CVE-2026-45458
Score EPSS : 0.000600000
CVE : CVE-2026-44819
Score EPSS : 0.000790000
CVE : CVE-2026-44821
Score EPSS : 0.000580000
CVE : CVE-2026-45455
Score EPSS : 0.000540000
CVE : CVE-2026-45469
Score EPSS : 0.001000000
CVE : CVE-2026-45485
Score EPSS : 0.000540000
CVE : CVE-2026-47635
Score EPSS : 0.000600000
CVE : CVE-2026-45466
Score EPSS : 0.000540000
CVE : CVE-2026-45456
Score EPSS : 0.001500000
CVE : CVE-2026-45486
Score EPSS : 0.000790000
CVE : CVE-2026-45471
Score EPSS : 0.000790000
CVE : CVE-2026-45459
Score EPSS : 0.000570000
CVE : CVE-2026-47293
Score EPSS : 0.000550000
CVE : CVE-2026-44824
Score EPSS : 0.000790000
CVE : CVE-2026-44818
Score EPSS : 0.000410000
CVE : CVE-2026-45460
Score EPSS : 0.000530000
CVE : CVE-2026-45475
Score EPSS : 0.000790000
CVE : CVE-2026-45596
Score EPSS : 0.000490000
CVE : CVE-2026-42907
Score EPSS : 0.001640000
CVE : CVE-2026-42913
Score EPSS : 0.000510000
CVE : CVE-2026-33828
Score EPSS : 0.001490000
CVE : CVE-2026-42903
Score EPSS : 0.001960000
CVE : CVE-2026-42972
Score EPSS : 0.000700000
CVE : CVE-2026-45487
Score EPSS : 0.000490000
CVE : CVE-2026-44805
Score EPSS : 0.000510000
CVE : CVE-2026-44803
Score EPSS : 0.001000000
CVE : CVE-2026-45607
Score EPSS : 0.000600000
CVE : CVE-2026-42968
Score EPSS : 0.000510000
CVE : CVE-2026-45600
Score EPSS : 0.001490000
CVE : CVE-2026-42906
Score EPSS : 0.000700000
CVE : CVE-2026-42970
Score EPSS : 0.000700000
CVE : CVE-2026-42984
Score EPSS : 0.000550000
CVE : CVE-2026-45604
Score EPSS : 0.000510000
CVE : CVE-2026-41092
Score EPSS : 0.000550000
CVE : CVE-2026-44811
Score EPSS : 0.000880000
CVE : CVE-2026-45603
Score EPSS : 0.000490000
CVE : CVE-2026-41108
Score EPSS : 0.000420000
CVE : CVE-2026-44812
Score EPSS : 0.001000000
CVE : CVE-2026-44809
Score EPSS : 0.000600000
CVE : CVE-2026-42916
Score EPSS : 0.000820000
CVE : CVE-2026-42915
Score EPSS : 0.002070000
CVE : CVE-2026-42971
Score EPSS : 0.000700000
CVE : CVE-2026-45658
Score EPSS : 0.000580000
CVE : CVE-2026-45591
Score EPSS : 0.016630000
CVE : CVE-2026-42910
Score EPSS : 0.000600000
CVE : CVE-2026-45592
Score EPSS : 0.000820000
CVE : CVE-2026-45598
Score EPSS : 0.000490000
CVE : CVE-2026-45597
Score EPSS : 0.000490000
CVE : CVE-2026-45655
Score EPSS : 0.000760000
CVE : CVE-2026-45654
Score EPSS : 0.000610000
CVE : CVE-2026-48574
Score EPSS : 0.000790000
CVE : CVE-2026-45602
Score EPSS : 0.000700000
CVE : CVE-2026-48576
Score EPSS : 0.002770000
CVE : CVE-2026-45639
Score EPSS : 0.000810000
CVE : CVE-2026-45634
Score EPSS : 0.000510000
CVE : CVE-2026-45594
Score EPSS : 0.000700000
CVE : CVE-2026-42912
Score EPSS : 0.000380000
CVE : CVE-2026-44804
Score EPSS : 0.000600000
CVE : CVE-2026-42908
Score EPSS : 0.000810000
CVE : CVE-2026-50508
Score EPSS : 0.000760000
CVE : CVE-2026-42829
Score EPSS : 0.000550000
CVE : CVE-2026-48575
Score EPSS : 0.000850000
CVE : CVE-2026-34335
Score EPSS : 0.000550000
CVE : CVE-2026-42978
Score EPSS : 0.000380000
CVE : CVE-2026-47654
Score EPSS : 0.000740000
CVE : CVE-2026-45653
Score EPSS : 0.000550000
CVE : CVE-2026-45642
Score EPSS : 0.001090000
CVE : CVE-2026-42911
Score EPSS : 0.000550000
CVE : CVE-2026-42905
Score EPSS : 0.000800000
CVE : CVE-2026-45586
Score EPSS : 0.001170000
CVE : CVE-2026-42837
Score EPSS : 0.000600000
CVE : CVE-2026-44810
Score EPSS : 0.000580000
CVE : CVE-2026-44807
Score EPSS : 0.000600000
CVE : CVE-2026-44801
Score EPSS : 0.000740000
CVE : CVE-2026-42973
Score EPSS : 0.000700000
CVE : CVE-2026-42979
Score EPSS : 0.000490000
CVE : CVE-2025-10263
Score EPSS : 0.000260000
CVE : CVE-2026-45608
Score EPSS : 0.000490000
CVE : CVE-2026-42983
Score EPSS : 0.000600000
CVE : CVE-2026-48570
Score EPSS : 0.000850000
CVE : CVE-2026-42977
Score EPSS : 0.000490000
CVE : CVE-2026-47656
Score EPSS : 0.000850000
CVE : CVE-2026-42989
Score EPSS : 0.000900000
CVE : CVE-2026-40409
Score EPSS : 0.001490000
CVE : CVE-2026-45606
Score EPSS : 0.000510000
CVE : CVE-2026-42828
Score EPSS : 0.000600000
CVE : CVE-2026-45640
Score EPSS : 0.000550000
CVE : CVE-2026-47648
Score EPSS : 0.001100000
CVE : CVE-2026-45636
Score EPSS : 0.001590000
CVE : CVE-2026-48565
Score EPSS : 0.001220000
CVE : CVE-2026-42836
Score EPSS : 0.000380000
CVE : CVE-2026-42974
Score EPSS : 0.001010000
CVE : CVE-2026-42980
Score EPSS : 0.001100000
CVE : CVE-2026-45656
Score EPSS : 0.000780000
CVE : CVE-2026-45637
Score EPSS : 0.000600000
CVE : CVE-2026-47288
Score EPSS : 0.003220000
CVE : CVE-2026-42904
Score EPSS : 0.001060000
CVE : CVE-2026-45599
Score EPSS : 0.000950000
CVE : CVE-2026-44799
Score EPSS : 0.000860000
CVE : CVE-2026-45638
Score EPSS : 0.000600000
CVE : CVE-2026-42981
Score EPSS : 0.001010000
CVE : CVE-2026-42991
Score EPSS : 0.000490000
CVE : CVE-2026-45593
Score EPSS : 0.000820000
CVE : CVE-2026-45490
Score EPSS : 0.000550000
CVE : CVE-2026-48573
Score EPSS : 0.002770000
CVE : CVE-2026-44808
Score EPSS : 0.000600000
CVE : CVE-2026-48566
Score EPSS : 0.000510000
CVE : CVE-2026-45601
Score EPSS : 0.000490000
CVE : CVE-2026-44802
Score EPSS : 0.000600000
CVE : CVE-2026-42992
Score EPSS : 0.000740000
CVE : CVE-2026-44813
Score EPSS : 0.000600000
CVE : CVE-2026-45605
Score EPSS : 0.000600000
CVE : CVE-2026-40404
Score EPSS : 0.001490000
CVE : CVE-2026-50507
Score EPSS : 0.000990000
CVE : CVE-2026-47289
Score EPSS : 0.000780000
CVE : CVE-2026-45635
Score EPSS : 0.003920000
CVE : CVE-2026-42986
Score EPSS : 0.000800000
CVE : CVE-2026-44815
Score EPSS : 0.003630000
CVE : CVE-2026-44814
Score EPSS : 0.000510000
CVE : CVE-2026-45641
Score EPSS : 0.001490000
CVE : CVE-2026-42993
Score EPSS : 0.000740000
CVE : CVE-2026-8863
Score EPSS : 0.000050000
CVE : CVE-2026-48568
Score EPSS : 0.000850000
CVE : CVE-2026-48563
Score EPSS : 0.000780000
CVE : CVE-2026-42987
Score EPSS : 0.000950000
CVE : CVE-2026-49160
Score EPSS : 0.012980000
CVE : CVE-2026-45491
Score EPSS : 0.000920000
CVE : CVE-2026-48583
Score EPSS : 0.000600000
CVE : CVE-2026-45657
Score EPSS : 0.001370000
CVE : CVE-2026-48578
Score EPSS : 0.000610000
CVE : CVE-2026-42914
Score EPSS : 0.000670000
CVE : CVE-2026-45648
Score EPSS : 0.000940000
CVE : CVE-2026-47653
Score EPSS : 0.000780000
CVE : CVE-2026-45588
Score EPSS : 0.000850000
CVE : CVE-2026-42909
Score EPSS : 0.000670000
CVE : CVE-2026-42969
Score EPSS : 0.001270000
CVE : CVE-2026-47652
Score EPSS : 0.000680000
CVE : CVE-2026-45595
Score EPSS : 0.000870000
CVE : CVE-2026-42985
Score EPSS : 0.000780000
CVE : CVE-2026-47291
Score EPSS : 0.002020000
CVE : CVE-2026-45591
Score EPSS : 0.016630000
CVE : CVE-2026-45491
Score EPSS : 0.000920000
CVE : CVE-2026-32193
Score EPSS : 0.000670000
CVE : CVE-2026-47643
Score EPSS : 0.001220000
CVE : CVE-2026-41098
Score EPSS : 0.000940000
CVE : CVE-2026-45842
Score EPSS : 0.000320000
CVE : CVE-2026-42902
Score EPSS : 0.000550000
CVE : CVE-2026-46119
Score EPSS : 0.000720000
CVE : CVE-2026-42789
Score EPSS : 0.000260000
CVE : CVE-2026-47639
Score EPSS : 0.000860000
CVE : CVE-2026-45845
Score EPSS : 0.000240000
CVE : CVE-2026-46124
Score EPSS : 0.000460000
CVE : CVE-2026-46082
Score EPSS : 0.000320000
CVE : CVE-2026-45464
Score EPSS : 0.000600000
CVE : CVE-2026-46065
Score EPSS : 0.000130000
CVE : CVE-2026-46227
Score EPSS : 0.000130000
CVE : CVE-2026-47631
Score EPSS : 0.000650000
CVE : CVE-2026-42496
Score EPSS : 0.000520000
CVE : CVE-2026-46185
Score EPSS : 0.000720000
CVE : CVE-2026-46064
Score EPSS : 0.000320000
CVE : CVE-2026-45988
Score EPSS : 0.000600000
CVE : CVE-2026-46112
Score EPSS : 0.000130000
CVE : CVE-2026-46196
Score EPSS : 0.000130000
CVE : CVE-2026-42790
Score EPSS : 0.000210000
CVE : CVE-2026-46063
Score EPSS : 0.000240000
CVE : CVE-2026-45583
Score EPSS : 0.000760000
CVE : CVE-2026-45500
Score EPSS : 0.000590000
CVE : CVE-2026-39833
Score EPSS : 0.000420000
CVE : CVE-2026-46233
Score EPSS : 0.000130000
CVE : CVE-2026-45504
Score EPSS : 0.000780000
CVE : CVE-2026-47292
Score EPSS : 0.001570000
CVE : CVE-2026-46114
Score EPSS : 0.000570000
CVE : CVE-2026-45650
Score EPSS : 0.000770000
CVE : CVE-2026-46080
Score EPSS : 0.000320000
CVE : CVE-2026-46231
Score EPSS : 0.000130000
CVE : CVE-2026-45835
Score EPSS : 0.000320000
CVE : CVE-2026-45996
Score EPSS : 0.000240000
CVE : CVE-2026-46229
Score EPSS : 0.000130000
CVE : CVE-2026-46019
Score EPSS : 0.000320000
CVE : CVE-2026-46173
Score EPSS : 0.000160000
CVE : CVE-2026-46195
Score EPSS : 0.000630000
CVE : CVE-2026-46204
Score EPSS : 0.000130000
CVE : CVE-2026-46214
Score EPSS : 0.000130000
CVE : CVE-2026-45647
Score EPSS : 0.000500000
CVE : CVE-2025-15649
Score EPSS : 0.000130000
CVE : CVE-2026-48560
Score EPSS : 0.004690000
CVE : CVE-2026-45502
Score EPSS : 0.000620000
CVE : CVE-2026-46027
Score EPSS : 0.000680000
CVE : CVE-2026-45591
Score EPSS : 0.016630000
CVE : CVE-2026-46040
Score EPSS : 0.000320000
CVE : CVE-2026-46236
Score EPSS : 0.000130000
CVE : CVE-2026-45481
Score EPSS : 0.000640000
CVE : CVE-2026-46113
Score EPSS : 0.000130000
CVE : CVE-2026-46137
Score EPSS : 0.000600000
CVE : CVE-2026-45841
Score EPSS : 0.000320000
CVE : CVE-2026-46072
Score EPSS : 0.000320000
CVE : CVE-2026-46159
Score EPSS : 0.000120000
CVE : CVE-2026-46190
Score EPSS : 0.000130000
CVE : CVE-2026-46142
Score EPSS : 0.000240000
CVE : CVE-2026-47634
Score EPSS : 0.000630000
CVE : CVE-2026-45468
Score EPSS : 0.000600000
CVE : CVE-2026-50292
Score EPSS : 0.000710000
CVE : CVE-2026-42835
Score EPSS : 0.001630000
CVE : CVE-2026-46209
Score EPSS : 0.000130000
CVE : CVE-2026-46031
Score EPSS : 0.000700000
CVE : CVE-2026-46186
Score EPSS : 0.000130000
CVE : CVE-2026-46002
Score EPSS : 0.000320000
CVE : CVE-2026-43503
Score EPSS : 0.000130000
CVE : CVE-2026-46101
Score EPSS : 0.000320000
CVE : CVE-2026-46099
Score EPSS : 0.000720000
CVE : CVE-2026-45989
Score EPSS : 0.000240000
CVE : CVE-2026-46091
Score EPSS : 0.000240000
CVE : CVE-2026-46024
Score EPSS : 0.000700000
CVE : CVE-2026-46106
Score EPSS : 0.000240000
CVE : CVE-2026-46037
Score EPSS : 0.000700000
CVE : CVE-2026-46116
Score EPSS : 0.000130000
CVE : CVE-2026-46083
Score EPSS : 0.000240000
CVE : CVE-2026-46151
Score EPSS : 0.000170000
CVE : CVE-2026-46220
Score EPSS : 0.000130000
CVE : CVE-2026-46127
Score EPSS : 0.000320000
CVE : CVE-2026-46176
Score EPSS : 0.000130000
CVE : CVE-2026-46146
Score EPSS : 0.000130000
CVE : CVE-2026-45836
Score EPSS : 0.000320000
CVE : CVE-2026-46178
Score EPSS : 0.000170000
CVE : CVE-2026-45846
Score EPSS : 0.000320000
CVE : CVE-2026-46133
Score EPSS : 0.001030000
CVE : CVE-2026-46005
Score EPSS : 0.000240000
CVE : CVE-2026-40371
Score EPSS : 0.000780000
CVE : CVE-2026-46069
Score EPSS : 0.000240000
CVE : CVE-2026-47298
Score EPSS : 0.000720000
CVE : CVE-2026-46122
Score EPSS : 0.000320000
CVE : CVE-2026-47637
Score EPSS : 0.000860000
CVE : CVE-2026-46022
Score EPSS : 0.000320000
CVE : CVE-2026-46103
Score EPSS : 0.000320000
CVE : CVE-2026-46226
Score EPSS : 0.000130000
CVE : CVE-2026-46043
Score EPSS : 0.000700000
CVE : CVE-2026-46120
Score EPSS : 0.000130000
CVE : CVE-2026-46198
Score EPSS : 0.000300000
CVE : CVE-2026-49975
Score EPSS : 0.004210000
CVE : CVE-2026-46189
Score EPSS : 0.000130000
CVE : CVE-2026-46011
Score EPSS : 0.000130000
CVE : CVE-2026-46128
Score EPSS : 0.000320000
CVE : CVE-2026-45503
Score EPSS : 0.000600000
CVE : CVE-2026-46012
Score EPSS : 0.000240000
CVE : CVE-2026-45479
Score EPSS : 0.000600000
CVE : CVE-2026-46197
Score EPSS : 0.000130000
CVE : CVE-2026-45467
Score EPSS : 0.000580000
CVE : CVE-2026-45999
Score EPSS : 0.000130000
CVE : CVE-2026-46180
Score EPSS : 0.000130000
CVE : CVE-2026-46038
Score EPSS : 0.000240000
CVE : CVE-2026-48962
Score EPSS : 0.000810000
CVE : CVE-2026-46206
Score EPSS : 0.000130000
CVE : CVE-2026-46000
Score EPSS : 0.000240000
CVE : CVE-2026-46234
Score EPSS : 0.000130000
CVE : CVE-2026-46109
Score EPSS : 0.000320000
CVE : CVE-2026-46062
Score EPSS : 0.000130000
CVE : CVE-2026-46108
Score EPSS : 0.000320000
CVE : CVE-2026-46049
Score EPSS : 0.000320000
CVE : CVE-2026-45458
Score EPSS : 0.000600000
CVE : CVE-2026-47640
Score EPSS : 0.000860000
CVE : CVE-2026-45997
Score EPSS : 0.000320000
CVE : CVE-2026-46070
Score EPSS : 0.000130000
CVE : CVE-2026-46150
Score EPSS : 0.000140000
CVE : CVE-2026-44819
Score EPSS : 0.000790000
CVE : CVE-2026-45840
Score EPSS : 0.000320000
CVE : CVE-2026-45484
Score EPSS : 0.006820000
CVE : CVE-2026-46300
Score EPSS : 0.002540000

# Consolidation des données

In [26]:
import pandas as pd
import numpy as np
df = pd.DataFrame.from_dict(list_cve)
df = df.replace('na', np.nan)
df['EPSS'] = df['EPSS'].astype(float)
df['CVSS'] = df['CVSS'].astype(float)
df

,ID ANSSI,Titre ANSSI,Type,Date,CVE,CVSS,Base Severity,CWE,EPSS,Lien,Description,Editeur,Produit,Versions affectées
0,CERTFR-2026-AVI-0699,Vulnérabilité dans Cisco Catalyst SD-WAN,Avis,None,CVE-2026-20245,7.8,None,CWE-116,0.00356,https://www.cve.org/CVERecord?id=CVE-2026-20245,A vulnerability in the CLI of Cisco Catalyst S...,Cisco,Cisco Catalyst SD-WAN Manager,"[20.1.12, 19.2.1, 18.4.4, 18.4.5, 20.1.1.1, 20..."
1,CERTFR-2026-AVI-0711,Multiples vulnérabilités dans les VPN Check Point,Avis,None,CVE-2026-50752,7.4,None,CWE-295,0.00031,https://www.cve.org/CVERecord?id=CVE-2026-50752,A weakness in the certificate validation logic...,checkpoint,Spark Firewalls,"[R80.20.X, R81.10.X, and R82.00.X]"
2,CERTFR-2026-AVI-0711,Multiples vulnérabilités dans les VPN Check Point,Avis,None,CVE-2026-50751,NaN,None,CWE-287,0.11841,https://www.cve.org/CVERecord?id=CVE-2026-50751,A logic flow weakness in Remote Access and Mob...,checkpoint,Spark Firewalls,"[R80.20.X, R81.10.X, and R82.00.X]"
3,CERTFR-2026-AVI-0712,Vulnérabilité dans Veeam Backup & Replication,Avis,None,CVE-2026-44963,9.4,None,CWE-502,0.00586,https://www.cve.org/CVERecord?id=CVE-2026-44963,A vulnerability allowing remote code execution...,Veeam,Backup and Replication,[0]
4,CERTFR-2026-AVI-0713,Vulnérabilité dans les produits Schneider Elec...,Avis,None,CVE-2026-8045,7.1,None,CWE-611,0.00057,https://www.cve.org/CVERecord?id=CVE-2026-8045,CWE-611 Improper Restriction of XML External E...,Schneider Electric,EcoStruxure™ IT Data Center Expert,[v9.1.1 and Prior]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339,CERTFR-2026-ALE-001,[MàJ] Multiples vulnérabilités dans Ivanti End...,Alerte,None,CVE-2026-1281,9.8,None,CWE-94,0.81586,https://www.cve.org/CVERecord?id=CVE-2026-1281,A code injection in Ivanti Endpoint Manager Mo...,Ivanti,Endpoint Manager Mobile,[]
1340,CERTFR-2026-ALE-002,[MàJ] Vulnérabilité dans Cisco Catalyst SD-WAN,Alerte,None,CVE-2026-20127,10.0,None,CWE-287,0.58950,https://www.cve.org/CVERecord?id=CVE-2026-20127,A vulnerability in the peering authentication ...,Cisco,Cisco Catalyst SD-WAN Manager,"[20.1.12, 19.2.1, 18.4.4, 18.4.5, 20.1.1.1, 20..."
1341,CERTFR-2026-ALE-002,[MàJ] Vulnérabilité dans Cisco Catalyst SD-WAN,Alerte,None,CVE-2022-20775,NaN,None,CWE-25,0.00385,https://www.cve.org/CVERecord?id=CVE-2022-20775,A vulnerability in the CLI of Cisco SD-WAN Sof...,Cisco,Cisco SD-WAN vEdge Router,"[18.4.303, 18.3.7, 19.3.0, 18.2.0, 20.1.12, 19..."
1342,CERTFR-2026-ALE-004,Vulnérabilité dans F5 BIG-IP Access Policy Man...,Alerte,None,CVE-2025-53521,9.8,None,CWE-121,0.08766,https://www.cve.org/CVERecord?id=CVE-2025-53521,When a BIG-IP APM access policy is configured ...,F5,BIG-IP,"[17.5.0, 17.1.0, 16.1.0, 15.1.0]"
1343,CERTFR-2026-ALE-005,[Màj] Vulnérabilité dans Microsoft Exchange Se...,Alerte,None,CVE-2026-42897,8.1,None,CWE-79,0.07856,https://www.cve.org/CVERecord?id=CVE-2026-42897,Improper neutralization of input during web pa...,Microsoft,Microsoft Exchange Server Subscription Edition...,[15.02.0.0]

In [24]:
df.describe()

             CVSS         EPSS
count  630.000000  1333.000000
mean     7.348730     0.029898
std      1.568659     0.149970
min      1.100000     0.000030
25%      6.800000     0.000210
50%      7.800000     0.000390
75%      8.100000     0.000790
max     10.000000     0.944120

In [27]:
df.isnull().sum()

ID ANSSI                 0
Titre ANSSI              0
Type                     0
Date                  1344
CVE                      0
CVSS                   714
Base Severity         1344
CWE                    501
EPSS                    11
Lien                     0
Description             12
Editeur                 13
Produit                 13
Versions affectées      29
dtype: int64